### ISSUE TITLE
Require Code Review: all 8 fields missing

### ISSUE THREAD

**Issue by nebster** [publiccodenet/standard#13]
• Measure
• What this does
• What this doesn’t do
• How to test
• Policy makers: what you need to do
• Management: what you need to do
• Developers and designers: what you need to do
• Further reading

**Comment by ElenaFdR** [comment]
Suggestion: to make the title active, flip this to 'review your code'? This relates to #6 .

**Comment by bvhme** [comment]
Good point, however this standard is not saying 'you should review your code' but 'you need to have someone else than the contributor review your code'.
