### ISSUE TITLE
first section in introduction doesn't mention the standard

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/standard#144]
I feel the introduction jumps too fast to explaining public code without introducing the standard, it's purpose, or the foundation.

The text under the last header `goals` gives this context, but only at the end.

**Comment by ElenaFdR** [comment]
I don't think this is necessary.
The homepage for the Standard (http://standard.publiccode.net/) does all of these things. Though we could duplicate the same paras at the top of the intro, it's unlikely anyone will get to the intro without interacting with the homepage.

**Comment by ElenaFdR** [comment]
Update: having read #144, these are all good additions and I approve them.
