### ISSUE TITLE
URL and Title mismatches

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/standard#153]
Not major, but we now have
Title
```
Code in the open
```
URL
```
coding-in-the-open
```

**Comment by clausmullie** [comment]
Similarly
```
Create reusable and portable code
```
```
reusable-and-portable-codebases
```

**Comment by clausmullie** [comment]
also true for version control and welcome contributions

**Comment by bvhme** [comment]
These should be fixed as a part of the 0.2.0 release process, **and not before**.

Otherwise the links for editing pages will break between the published standard and the edit page on GitHub.

**Comment by Ainali** [comment]
When this is solved, don't forget to add/update redirects.

**Comment by Ainali** [comment]
Let's make the title and the file name to match as close as possible.
