### ISSUE TITLE
We now lay out tests for 'SHOULD' requirements

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/standard#155]
Is this consistent? 

Does something need to pass all tests to be certified? If so, the corresponding requirements should become 'MUST'

See example in
```
Bundle policy and source code
```
First test is direct mirror of a SHOULD requirement
Second test only works if business process modelling is used (I think?), which is not a requirement

**Comment by Ainali** [comment]
Yes, this is consistent. The how to test is aimed to be a guide for anyone testing, not to set the bar for the requirement. We may very well have guidance even on MAY requirements if it's non-obvious how to do it. As such I believe we can close this issue.
