### ISSUE TITLE
Glossary 'public code' item has typo 'civil' where should be 'civic'

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#166]
In the glossary the notion of _public code_ mentions _civil code_ where we meant _civic code_

## How to fix

1. Edit the file [`glossary.md`](https://github.com/publiccodenet/standard/blob/develop/glossary.md) to replace `civil code` with `civic code`.
2. Commit your changes with a description of what you've done it the commit title (for example: `Fixed typo 'civil' to 'civic'`) and mentioning it fixes this issue in the body text (`fixes #166`)
3. Create a pull request

And you are done!

**Comment by ElenaFdR** [comment]
This is now fixed.
