### ISSUE TITLE
Template: Reference back to Foundations' core value propositions 

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/standard#167]
Once we have more clearly defined our set of core value propositions through our user mapping and research with partners

example:
```
a) cost effective, b) local control, c) more innovation potential, d) quality services, e) less risk
```
We could reference directly back to these 4-5 value propositions in our standard, either in the 'what this does' section, or in the 'for managers/policy makers/developers&designers section. This will help for each criteria in the standard drive home clearly why it's important and what the direct impact of this criteria is. 

Example:
```
For good documentation --> less long term risk (technical debt) as you can understand what old piece of code do and why/how, as well more local control as code is more easily editable, as well as less costly to go and edit these
```

**Comment by ericherman** [comment]
The "Why this is important" sections should speak for themselves, regardless of why the Foundation for Public Code is a valuable institution.

If the "Why this is important" sections are weak or need improvement, I'd like to see new issues or PRs for each.

**Comment by ericherman** [comment]
Closing this, as we have no new comments.
