### ISSUE TITLE
The illustrations are not in the Print PDF when generated

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#174]
In the current PDF and print version I manually added the illustrations with a PDF editor, however these should be in the HTML/CSS so they can be dependably regenerated.

**Comment by Ainali** [comment]
Is this still really the case? https://standard.publiccode.net/print.html have images in it.

**Comment by bvhme** [comment]
This is resolved. I get images when I generate the PDF. Let's close this.
