### ISSUE TITLE
The glossary is out of sync with the one in the about.publiccode.net

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#176]
Perhaps we can make one unified glossary and import here what we need from that one or something similar.

Ideally we have one glossary for the entire Foundation for Public Code

**Comment by ElenaFdR** [comment]
Yes! Also one version of how the Foundation's code certification process works.

**Comment by ElenaFdR** [comment]
After examining both glossaries, I don't think it makes sense to include the full About glossary in the standard - there are terms in it that don't appear in the Standard.
Instead, I propose considering the Standard's glossary as a subsection of the About's glossary. This means making sure that the terms that appear in the Standard's glossary are:
1) always included in the full About glossary
2) mirror the definition in the About

**Comment by ElenaFdR** [comment]
#191 updates the Standard glossary. I still need to separately update the About glossary to reflect the Standard.

**Comment by ElenaFdR** [comment]
About [#191](https://github.com/publiccodenet/about/pull/211) updates the About glossary to mirror the Standard glossary.
Standard #196 includes further improvements made to both glossaries.

**Comment by bvhme** [comment]
So, this issue can be closed?

**Comment by ElenaFdR** [comment]
Only when the open pull requests above have been merged.
