### ISSUE TITLE
Create some amazingly easy 'good first issue's

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#177]
To give new contributors a simple way to get started.

**Comment by viraldevpb** [comment]
Hey, @bvhme can u explain to me what this issue is all about?

**Comment by ericherman** [comment]
@viraldevpb, This issue is to remind all of us who are creating or resolving issues to think about the issues from the perspective of how suitable they are for a relatively new contributor to the Standard.

**Comment by ericherman** [comment]
We now use the [good first issue ](https://github.com/publiccodenet/standard/labels/good%20first%20issue) tag if appropriate.
