### ISSUE TITLE
Describe release management for future versions of the Standard (including testing the version with other people and how to generate PDF)

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#178]
Created by @ElenaFdR on the Kanban board

**Comment by clausmullie** [comment]
Has this issue been addressed by #365 ?

**Comment by ericherman** [comment]
https://github.com/publiccodenet/standard/pull/365 and previous commits addresses this reasonably well. There is room for some additional detail work and those details can be covered as specific issues.
