### ISSUE TITLE
You can't easily find the PDF of the standard on the site

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#183]
I'd add a line to the `index.md` that links to the GitHub repository 'releases' page where PDFs of every version can be downloaded.

**Comment by Ainali** [comment]
Another idea is to add a line that have a direct link to the latest pdf and a link to the releases page with all older versions. The upside is that it is fewer clicks for the person looking for it (and potentially better SEO). The downside is that we need to change the link with every release.

**Comment by ericherman** [comment]
(resolved)
