### ISSUE TITLE
Bullet sounds skeptical about policymakers' ability to understand code

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#197]
This bullet in [bundle policy and source code](http://standard.publiccode.net/criteria/bundle-policy-and-code.html) is easy to read in a deeply sarcastic tone of voice:

```
* Try to periodically understand what the non-policy code in the codebase does
```
Suggested alternative:
```
* Check in regularly to understand how the non-policy code in the codebase has changed and what it's doing now

**Comment by ElenaFdR** [comment]
@bvhme Any thoughts?

**Comment by bvhme** [comment]
I agree, let me do another suggestion:

> * Check in regularly to understand how the non-policy code in the codebase has changed and whether that is still in line with the intentions of the policy.

**Comment by ericherman** [comment]
(merged)
