### ISSUE TITLE
Add a requirement for a responsible disclosure channel

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#198]
As suggested by Michiel Leenaars

**Comment by Beanow** [comment]
Definitely important for trust and sustainability. I've made the case (https://github.com/sfosc/sfosc/pull/33) this may even be more important from a moral and sustainability point of view than trying very hard at making it secure proactively.

Besides setting up the channel, it should be paired with a commitments how disclosures are handled. As the whole point is to reduce risk of information falling into the wrong hands and getting a fix out as soon as reasonably possible.

**Comment by ElenaFdR** [comment]
Would this be included in 'Document your code', 'Open to contributions' or somewhere else?

**Comment by Beanow** [comment]
We had another discussion round on this: https://github.com/sfosc/sfosc/issues/85

The short version is, we suspect poor security practices can cause damage to the open source ecosystem beyond the project in question. So there is a moral obligation to work on security, to prevent wider spread issues.

I think it covers several aspects,
- Transparency (for the disclosure part)
- Collaboration (standardized publications where applicable for example)
- Maintainer responsibilities
- Best practices
- ...

So I think it wouldn't fit very cleanly in any one section.

**Comment by ElenaFdR** [comment]
This issue has stalled due to discussion in the [30 August 2019 community call:](https://github.com/publiccodenet/standard/issues/211#issuecomment-530374449).

**Comment by ericherman** [comment]
https://standard.publiccode.net/criteria/make-contributing-easy.html states:
* The codebase MUST include instructions for how to privately report security issues for responsible disclosure.
