### ISSUE TITLE
Public Code can be defined more clearly

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#203]
The current definition of Public Code is not in line with other content:

* Inclusive is missing from the mission list (is it important, since this is based on an outdated mission)
* Many vague terms

Perhaps we can clearly redefine this.

**Comment by ElenaFdR** [comment]
Clean up together with #208.

**Comment by ericherman** [comment]
We have received input from policy makers that we should be clear about when speaking about source code and policy text.

See issue #496

**Comment by ericherman** [comment]
Is the [new](03e18387e702333e04940437b9fcc58620163f9d) definition of Public Code in https://github.com/publiccodenet/standard/blob/develop/glossary.md#public-code sufficient?

**Comment by Ainali** [comment]
I agree that that definition is an improvement. Let's close this for now and re-open (or create a new issue) if confusion prevails.
