### ISSUE TITLE
Add easier/manual ways of providing feedback to the contributor guide

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#205]
Reading the printed version @EdoPlantinga was overwhelmed by the complexity (especially for non-nerds). Perhaps we can mention emailing feedback before diving into how to make changes on GitHub.

**Comment by ElenaFdR** [comment]
I've added a sentence offering <info@publiccode.net>, but it might be more useful to create <standard@publiccode.net>.

**Comment by bvhme** [comment]
Maybe <standard-feedback@publiccode.net> would be easier to use. I'm guessing this should be a group, and who needs to be in it?

**Comment by ElenaFdR** [comment]
👋

**Comment by ericherman** [comment]
We have mailing list:
* standard@lists.publiccode.net

* https://lists.publiccode.net/mailman/postorius/lists/standard.lists.publiccode.net/

And soon it will be in the contributing guide: #422

**Comment by ericherman** [comment]
Resolved by #503
