### ISSUE TITLE
SPDX headers for licenses

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#212]
Michiel suggested a requirement for SPDX license files, mainly for in hardware use.

**Comment by ericherman** [comment]
The standard says each file SHOULD include a copyright notice and a license header.

I would suggest that machine discoverability of license is a SHOULD as well, but not specify *how*.

For any codebase the Foundation for Public Code stewards, I'd encourage that it adopts SPDX, but that at the standard level this is too specific. Just as the Standard specifies that version control is a MUST, yet doesn't name git or svn or whatever -- even though the Foundation for Public Code uses git exclusively.

Perhaps a specific technology is better suited a How To Test option or guidance for developers and designers.

**Comment by Ainali** [comment]
Whether or not we should push for a specific standard I believe is most often dependent on if there are other competing standards and we prefer one over the other for some reason. If it in reality really is only one standard, then perhaps we don't need to push it, but then we could also help by pointing towards it. Not in the requirements though, and maybe not even in How to test, but as line in what Developers and designers need to do as a suggestion.

**Comment by ericherman** [comment]
Should have been closed with the merge of #418
