### ISSUE TITLE
No navigation in web version

### ISSUE THREAD

**Issue by nomorepanic** [publiccodenet/standard#217]
Documentation pages usually provide the index on each page for ease of navigation; some of the finer documentations introduce the next chapter at the end and provide a link for it.

The web version has neither and this means that a reader, once finished reading has to go back to the index.

**Comment by bvhme** [comment]
This is absolutely right, and comes for now mainly from trying to keep the technical system simple to use. We should definetely update this to make it more usable.

**Comment by ElenaFdR** [comment]
Feedback from Code for NL meetup:
Please expose nav when you're within a page so you can see (and jump to) what the other criteria are while you're reading.

**Comment by ericherman** [comment]
See also #512

**Comment by ericherman** [comment]
Resolved via #535
