### ISSUE TITLE
Recommend responding to issues and pull requests in a timely manner

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#221]
As suggested by @imingueza in an e-mail:

> Reply to incoming issues and Pull Requests within 48 hours and other interesting info contained https://amsterdam.github.io/guides/track-open-source-health/ it would be nice to assure that appears also in the Standard for codebases.

**Comment by ericherman** [comment]
The criterion [Require review of contributions](https://github.com/publiccodenet/standard/blob/develop/criteria/require-review.md)  includes the requirement:

`* Reviews SHOULD happen within two business days.`

Is this sufficient?

**Comment by raboof** [comment]
(wow, that seems rather ambitious)

**Comment by ericherman** [comment]
> (wow, that seems rather ambitious)

This has been discussed on community calls, and perhaps should be discussed again.

The consensus on the last call was that visible feedback should happen within two days, and that may not always contain a completed review.

If someone feels this requirement needs sharpening, please note that here in this issue. And, as always, text change proposals welcome!

**Comment by ericherman** [comment]
If no suggestions for wording are proposed by 2021-12-08, I suggest closing the issue.

**Comment by ericherman** [comment]
closing

**Comment by Ainali** [comment]
Actually closing :)
