### ISSUE TITLE
Add engineering guidelines (in addition to Standard criteria 13 - use a coherent style)

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#222]
Questions to consider:

are you using a standard library?
is it buildable from open source?

**Comment by ElenaFdR** [comment]
The style criterion has evolved from simply being coding style to also including a general comms style guide. Do engineering guidelines also belong under this point, or is it worth separating them - either because there's too much detail in this to merge into the current content without overwhelming it, or because we other 'follow coding best practice' requirements to bundle with this?

**Comment by ericherman** [comment]
The section `Developers and designers: what you need to do` could include additional guidance to build out the engineering guidelines for the codebase.

**Comment by Ainali** [comment]
Fixed by #540
