### ISSUE TITLE
Add nuance on where non-English is acceptable

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#223]
Current thinking: non-living documents in original language can be attached so long as their original publication date is clear and there's an English introduction.
For example:
- historical policy papers
- the comms plan/comms rollout for new municipal software
- the law/legal framework

**Comment by ElenaFdR** [comment]
Separately: @nebster feedback from potential member: members do not have the resources to translate entire policy frameworks (example: 5000 page documents voted on by a city council) into English, so we need to accept an English overview.
"how we describe the module of civic code that we need for the Standard that is still doable for a member"

**Comment by ElenaFdR** [comment]
Potential template for the English policy overview: https://haarlem.github.io/bpmn-processen/AanvraagOntheffingStraatoptreden/README.html

**Comment by ericherman** [comment]
I suggest that we split:
 * All code and documentation MUST be in English.
 
into two requirements so that we may more easily add appropriate nuance to each.

Perhaps resulting in something a bit like:
 * All code MUST be in English, except where required to execute as policy.
 * All codebase documentation MUST be in English."

Which I think may more clearly allow for instance linking to a law which is not English, as that is not documentation about the codebase, specifically.

**Comment by maukoquiroga** [comment]
### Situation

In the future, we want public code to be the "official interpretation" of policy/legislation - so it's transparent, accountable, traceable, amendable, ...

### Complication

Countries define their policy in one or all of their officially recognised languages, English or not.

For public code to be an official interpretation of a country's policy/legislation,  it has to be in at least one of the legally recognised languages of that country to be recognised as an official interpretation of the policy.

### Proposal

- Interpretation of the policy herself (mostly nouns, models) must be in at least all the required languages by the country (for example English and French in Canada)

- Policy-independent code (for example "calculate the marginal rate of X") should be at least in English.

**Comment by ericherman** [comment]
#527 is a start but does not address non-english policy.

My current thinking is that policy which does not have an official translation into english, but informs codebases should be summarized in english to the level of detail that allows contributors and collaborators to understand the connections between policy and the codebase.

Should a statement about this be added in "Use Plain English" or "Bundle Policy and Code"?
