### ISSUE TITLE
'Bundle policy and source code' can be interpreted very wide

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#224]
The standard for 'Bundle policy and source code' is meant to enable reusers to understand what policy they might need to include with the software.

In the same way that you have to configure the code to run it you need to configure the policy to run it.

This link needs to be guaranteed in the software, however the bar to do this needs to be low enough to be possible.

As I hear it one possible member understood this as bundling all related policy, how do we make clear that it is about the policy which is related to the code it is based on.

**Comment by ElenaFdR** [comment]
Related issue: #223.

**Comment by ericherman** [comment]
In light of https://blog.publiccode.net/community%20call/2022/01/11/notes-from-community-call-6-january-2022.html , let's see what a good example repository teaches us about possible wording changes.

**Comment by Ainali** [comment]
If we solve #560  and put the "why this is important" before the requirement it might be much easier to understand and less confusion.

**Comment by ericherman** [comment]
Reasonably addressed by #560, we can re-open this if someone wishes to put forward a pull request to further improve it.
