### ISSUE TITLE
There is no mention of a `CONTRIBUTING` or `README` file

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#225]
However, there is a mention of a `GOVERNANCE` file. This seems weird, either we go with these conventions or not.

**Comment by ElenaFdR** [comment]
Where is there no mention?

**Comment by bvhme** [comment]
In the criteria, nowhere is having these files mentioned as a
recommendation.

**Comment by Ainali** [comment]
Closed by #228
