### ISSUE TITLE
Potential new requirement: clean coding

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#231]
From the Code for NL meetup:
Keep your data and your code separate.

**Comment by ericherman** [comment]
For any data which can change between installations or over time, this should be covered by:

> The codebase MUST be developed to be reusable in different contexts.

and

> Configuration SHOULD be used to make code adapt to context specific needs.

Thus, while more could be added to "Developers and designers: what you need to do", a new requirement does not appear to be needed.
