### ISSUE TITLE
Require a roadmap

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#233]
From the Code for NL meetup:

As a dev, this is vital for:
- feature planning and release planning
- creating a governance structure for getting features into the roadmp

Can this be added to 'document your objectives' so it becomes 'document your objectives and planning'?

**Comment by Ainali** [comment]
There is a SHOULD for having a publicly available roadmap in [Welcome to contributions](https://standard.publiccode.net/criteria/open-to-contributions.html). Is that enough?
