### ISSUE TITLE
Require machine readable API specifications

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#237]
E.g. OpenAPI. As suggested by @serverbrain.

**Comment by ericherman** [comment]
For web-based APIs I'd like to see https://github.com/OAI/OpenAPI-Specification/ adopted, that said, how much does this make sense in other contexts? Is there a wording which makes sense generally?

A link to the OpenAPI Specification could fit into further reading of "Create reusable and portable code", would that be a start?

**Comment by raboof** [comment]
TBH while I like machine-readable API specifications, I'm not sure it makes sense to require them from the "public code" perspective: I guess you could argue having machine-readable API specs makes collaboration easier, but it's kind of a tangent. If we do want to go that way https://grpc.io/ might be worth a mention.

**Comment by ericherman** [comment]
I can imagine a policy of a public organization to create HTTP-based, machine readable APIs. However, HTTP APIs (e.g.: REST) are not the only ways nor always the best ways to build an API, even a network accessed API.

For example, if some organization is building a distributed system today, they might choose ZeroMQ to try have something like golang's channels with socket-like inter-process communication over the network .... While this could be a perfectly reasonable choice, it wouldn't neatly fit into the machine-readable API world.

Regardless, I agree with @raboof that machine readable APIs seem like a second-order way to encourage collaboration or re-use. That said, a mention in "Further reading" seems worth consideration.

**Comment by Ainali** [comment]
> That said, a mention in "Further reading" seems worth consideration.

The suggestion of making an addition to further reading was discussed in the [backlog pruning session last Thursday](https://blog.publiccode.net/community%20call/2022/03/11/pruning-the-oldest-issues.html) and already submitted as a pull request.
