### ISSUE TITLE
propose a criterion for the Standard to ensure a codebase is easily "findable"

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#264]
What's the minimum the Standard for Public Code should require of a codebase with regards to marketing? Is it something like, "MUST have a unique enough name that it is easily findable via a major search engine" or is it more sophisticated -- something about searching for functionality? How would we word the MUSTs, SHOULDs, and MAYs here?

**Comment by Ainali** [comment]
This will be the topic of [the community call on June 2](https://hackmd.io/-OegeqvoThCbAsw3c3gIjw?view).

**Comment by ElenaFdR** [comment]
What about encouragement to submit a codebase all potentially relevant software catalogs or indices?

Catalog examples:
- Inter-American Development Bank's [Code for Development](https://code.iadb.org/en/about)
- Italy's [national software catalog](https://developers.italia.it/en/software.html)
- the Intergovernmental Software Collaborative's [Intergovernmental Software Cooperatives](https://softwarecollaborative.org/cooperatives/)
- the Civic Tech Field Guide's [Tech list](https://directory.civictech.guide/tech)

**Comment by ElenaFdR** [comment]
Ooh, something that didn't come up in our community call was mandatory publication of metrics (#265), a linked issue here. Shall we consider that as well in any potential new marketing criterion draft?

**Comment by ericherman** [comment]
Regarding the connection to Open Data which was mentioned, the "Findable" aspect of the FAIR[1] Principles emphasizes metadata, more detailed than what "Create reusable and portable code" contains. Perhaps adding some detail would be useful.

[1] From [https://www.go-fair.org/fair-principles/](https://www.go-fair.org/fair-principles/):
> In 2016, the ‘[FAIR Guiding Principles for scientific data management and stewardship’] (http://www.nature.com/articles/sdata201618) were published in Scientific Data. The authors intended to provide guidelines to improve the Findability, Accessibility, Interoperability, and Reuse of digital assets.

**Comment by ericherman** [comment]
As I've reflected on this, I see "Findability" and "Documentation" as better ways to frame requirements of public code codebases; "marketing" does not click as the right framing.

The essence of our talk was about "finding" a codebase, once found, there's all sorts of possibilities regarding presentation of various forms of documentation. Especially the "MUST" that we discussed: being able to find by descriptions of the problem to be solved without knowing the codebase name.

Some of the "MAY" requirements we discussed are about "findable" (for example having a web site a recognizable domain) but much of the conversation was were about the form and contents of the documentation (for example a rich website like we helped create for other codebases).

**Comment by Ainali** [comment]
> This will be the topic of [the community call on June 2](https://hackmd.io/-OegeqvoThCbAsw3c3gIjw?view).

And here are [the notes from the call](https://blog.publiccode.net/community%20call/2022/06/08/notes-from-community-call-2-june-2022.html).

**Comment by Ainali** [comment]
Fixed by #630
