### ISSUE TITLE
Standard lacks statements regarding operational requirements

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#267]
Are operational requirements (hosting requirements etc.) documented and tested?

**Comment by ericherman** [comment]
I'd like to see all codebases be specific in their documentation about what are the build-time and runtime dependencies.

**Comment by Ainali** [comment]
Agreed. Finding it out only when building or running (or reading the code) is a bit too late. Having it explicit in the documentation would be setting a very good example by being as transparent as possible.

**Comment by ElenaFdR** [comment]
We could require people to track codebase dependencies in their repo, for example using functionality like Github's dependency graph (findable under 'insights').

**Comment by Ainali** [comment]
An online work session for this is planned for 25 April, 11.00 CEST. React with the rocket if you want to join it.
