### ISSUE TITLE
Submit external links to the Internet Archive

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#275]
The pull request about archiving got me thinking about something related. We have several links to other websites in the standard and thus are a bit dependent on external parties. Would it make sense to, before each release of the standard, go through all external links and submit them to the [Wayback Machine](https://web.archive.org) so that they are available somewhere on the web even if the website we refer to goes down? We don't have that many, so this could probably be done manually (even though an automated way would be good to make sure not to miss any due to human error).

**Comment by ericherman** [comment]
Especially if we could easily automate this, I am in favour adding it to the release process.

**Comment by felixfaassen** [comment]
@ericherman  We might be able to use html_proofer to generate a list of external sites and submit those to Wayback machine? https://jekyllrb.com/docs/continuous-integration/travis-ci/

**Comment by ericherman** [comment]
Yes, that's certainly better than this hack: https://pastebin.com/raw/aDAn1JMY

**Comment by bvhme** [comment]
And since we already use _htmlproofer_ for checking our links that seems like a good solution :)

**Comment by ericherman** [comment]
At release, I'm calling https://github.com/ericherman/code-snips/blob/master/shell/to-archive-org.sh by hand ... I'm not very happy with this script, even though it works.

One of the issues of sending links to archive.org is being mindful of the limiting ... perhaps this is a good candidate something more cron-job like?

**Comment by Ainali** [comment]
A work session is being planned for 30 June, react with a :rocket: if you want to be invited.
