### ISSUE TITLE
Explicitly mention internationalization as good practice?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#277]
When developing a codebase for internal use it is rare to add support for i18n. Perhaps we should mention it somewhere explicitly? It would probably fit under [the section for developers and designers in Create reusable and portable code](https://standard.publiccode.net/criteria/reusable-and-portable-codebases.html#developers-and-designers-what-you-need-to-do) by rephrasing the first bullet point into 

> Source should be designed for reuse by other users and organizations, for example by being ready for internationalization

**Comment by ElenaFdR** [comment]
This makes sense! Can we provide guidance for how to get started for people who haven't previously had to think about how to make something usable outside of their own context? (For example, it looks like there's [extensive AngularJS guidance](https://docs.angularjs.org/guide/i18n) - would this be helpful even for people not working in Angular?)

**Comment by ElenaFdR** [comment]
Considering assessement: is this easily measurable? Could an external person look at a codebase and tell if internationalization has been appropriately applied? (Would a codebase maintainer asked this answer in a binary yes/no, or a percent, or would the answer always be an explanation?)

**Comment by Ainali** [comment]
Some things could be discovered. But i guess it is not easily measurable by either binary or percentage scale. But you could have sub-questions if different parts are prepared, eg. no hardcoded text in the UI, currency, date, numbers, plurals, right-to-left languages etc. It is hard to be fully covered, but some small measures go a long way.

**Comment by Ainali** [comment]
An online work session for this is planned for 9 May, 11.00 CEST. React with the rocket if you want to join it and I'll send you an invite.

**Comment by ericherman** [comment]
If lack of internationalization prevents a codebase from being developed in such a way that it is reusable in different contexts, then this could already be covered. While an explicit requirement may not be needed, certainly guidance would be good to add.
