### ISSUE TITLE
Maintain version control: add "SHOULD" use a *distributed* version control system

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#285]
It is probably too much to say MUST, but SHOULD seems quite reasonable.

Note we see this in existing places, e.g. on the [GDS website](https://www.gov.uk/service-manual/technology/maintaining-version-control-in-coding) we can read:

You should use a distributed version control system so that:

    everyone involved in the process has a full copy of the code and its history
    it’s easier for developers to create ‘branches’ in their code to explore new features or approaches without encroaching on other work
    developers can continue to work when the network is unavailable, making small incremental commits, merging their changes back with everyone else’s at a later date

**Comment by bvhme** [comment]
I think this is very good, as in addition to GDS' stated rule I believe that the ability to fork and re-merge means that it is significantly easier to work together for organizations on the same codebase.

I'd put this in as a strong SHOULD.
