### ISSUE TITLE
Change MAY to SHOULD for code of conducts?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#287]
[The Internet Health Report](https://internethealthreport.org/2019/) from Mozilla (presented during DecidimFest) has an entire chapter on the importance of Code of Conducts. In light of that I feel it might be appropriate to raise the criteria for having them from MAY to SHOULD.

[Currently it says](https://standard.publiccode.net/criteria/open-to-contributions.html):
> The codebase MAY include a code of conduct for contributors

**Comment by bvhme** [comment]
I agree that this is best practice in the open source community at large.

The reasoning for making it a 'MAY' was that these codebases are developed largely in a professional environment and thus are already largely bound by professional criteria. This is perhaps not convincing enough of an argument.

**Comment by ericherman** [comment]
Consensus is to remain OPTIONAL for now.
