### ISSUE TITLE
Add a public roadmap for the standard to Readme?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#292]
Right now there is no public roadmap for the standard. It would be nice to add it to the readme so that people interested in the standard can see what the plans are.

**Comment by bvhme** [comment]
I like this idea. Is it perhaps that there is no roadmap because we've not done the work of defining what its future will look like and what we want to add when.

**Comment by Ainali** [comment]
In [the last community call](https://blog.publiccode.net/community%20call/2021/01/25/notes-from-community-call-7-january-2021.html) we also discussed milestones for future work, but made no decisions. Posting this comment for discoverability later.

**Comment by Ainali** [comment]
Will be the topic of the community call on 7 July.

**Comment by Ainali** [comment]
> Will you publish the call afterwards?

@oxcar Yes, on our blog. The [PR is already here](https://github.com/publiccodenet/blog/pull/362).
