### ISSUE TITLE
Style: standardise statements under 'how to test'

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#30]
Suggestion: frame these as either positive statements or questions (not a hybrid).
Current example from Code in the open:
"Is the current version of the source published on the internet where it can be seen from outside your organization and without the need for any form of authentication."
Suggested alternatives:
- Is the current version of the source published on the internet where it can be seen from outside your organization and without the need for any form of authentication?
- The current version of the source is published on the internet where it can be seen from outside your organization and without the need for any form of authentication.

**Comment by ElenaFdR** [comment]
Style choice = present tense factual statements. 
Example: 
* It is clear where to get the newest version

**Comment by bvhme** [comment]
Great, I think this is helpful.
