### ISSUE TITLE
New requirement about intellectual property

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#307]
During our brief governance meeting today @bvhme floated the idea of making it a requirement that intellectual property in public code projects should be retained by those making contributions. The argument for this is that many civil servants are prohibited by local national law to sign it away. I really like this idea and it would probably fit well in [Publish under an open license](https://github.com/publiccodenet/standard/blob/develop/criteria/open-licenses.md).

**Comment by Ainali** [comment]
Is this a MUST or a SHOULD? I am leaning towards the former, but perhaps that is too strict?

**Comment by bvhme** [comment]
I would say that as we're helping organizations to enable them to work with public organizations in different contexts: that disallowing a whole swath of them to contribute by creating an intellectual property structure that makes it illegal for them to contribute, seems like a bad idea.

So I think I'd opt for a `MUST` here.

**Comment by ericherman** [comment]
See also CLA issue: https://github.com/publiccodenet/standard/issues/211
And related PR: https://github.com/publiccodenet/standard/pull/255

**Comment by Ainali** [comment]
Solved by #313
