### ISSUE TITLE
Clarify intersection of policy-defined vocabulary and Use Plain English

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#308]
The Standard should reflect how code which implements a specific standard or legal policy which requires or defines words which are not English is expected to handle the "Use Plain English" requirement.

**Comment by ericherman** [comment]
given:
* There SHOULD be no acronyms, abbreviations, puns or legal/domain specific terms in the codebase without an explanation preceding it or a link to an explanation.

Legal context may require a systems to create API with non-english words, there should be documentation describing it (perhaps a glossary) AND should link to the policy (bundle policy and code) which makes this clear.

As Configuration rather than Code should be preferred for adapting to specific contexts, it connects to different contexts may require different objects/names.

**Comment by nicorikken** [comment]
Making translations explicit will help show the outside world the project cares and is open/willing to work on it to support new use-cases.

**Comment by ElenaFdR** [comment]
Advantages to tracking specific terms to be translated as issues that are each tagged to a 100% translation milestone:

- shows external parties that there *is* a commitment to full English 
- helps people (inside and outside project) clearly see how much progress there's been/how much still need to be done (which may help motivate)
- creates a dedicated space for discussion of accurate translations which then become part of the searchable history of the codebase
- lets non-developers join discussions of the most accurate translation (can expand the contributor community)

**Comment by ericherman** [comment]
Resolved
