### ISSUE TITLE
Bundle policy & code: questions on ##Measure

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#31]
* Policy SHOULD be provided in machine readable and unambiguous formats
-> Can we provide examples for what this looks like in practice? (Which machines, which markup, to what end?)
--> now that I've read to the end, we need to add links to:

+ Business Process Model Notation, 
+ Decision Model Notion
+ Case Management Model Notation

* Continuous integration tests SHOULD validate the source code and the policy are executed coherently
-> how will CI test how policy's implemented?

**Comment by ElenaFdR** [comment]
Also for #measure:
Policy SHOULD be provided in machine readable and unambiguous formats

Can we provide examples for what this looks like in practice? (Which machines, which markup, to what end?)

**Comment by bvhme** [comment]
Some links to BPMN can be found here as well: https://github.com/publiccodenet/standard/pull/33/files

Feel free to add some links, the wikipedia or OMG links should be fine.

CI tests can test using machine-readable notations for policy and seeing whether the scenarios meet the outcomes if they are fed in.
