### ISSUE TITLE
Not all MUST criteria have a clear test in the "How to test" section

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#314]
As mentioned in Issue https://github.com/publiccodenet/standard/issues/80 and Issue https://github.com/publiccodenet/standard/issues/141, the section 'How to test' has several problems:

1. They don't cover all the MUST
2. Not all of them are clear tests, but more like key evaluation concepts

Can we ensure that each criterion has a clear test and make it similarly clear which requirement each test covers?

**Comment by Ainali** [comment]
A work session is scheduled for 19 July 14.30 CEST. React with :rocket: if you want to get an invitation
