### ISSUE TITLE
Version control or compare changes?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#316]
The criteria [Maintain version control](https://standard.publiccode.net/criteria/version-control-and-history.html) has the requirement:

> You SHOULD prefer file formats that can easily be version controlled.

Technically, modern version control software can handle most files with ease. But what we do want to say with this is more precise, we want to be able to compare changes easily, and not only on a technical level, but on a human readable level. Can we make this more clear in the requirement or is this nitpicky and actually obvious?

**Comment by ericherman** [comment]
Indeed, the wording should be improved to include meaningful diff.

**Comment by bvhme** [comment]
Yes, file formats where the changes between files can clearly be viewed and understood.
