### ISSUE TITLE
Providing a definition what transparent, accountable, understandable means in the context of public software

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/standard#317]
I'd like to report an issue in `introduction.md`

In the section "Designing truly public software" we define what public software must be.

> Public software must therefore be:
> 
> transparent
> accountable
> understandable for its constituents
> It must reflect the values of the society it serves, for example by being inclusive and non-discriminatory.

We could provide a bit more context toward the definition of what transparant, accountable and understandable for its constituents would mean in this context.

Here is a first suggestion. Help with better wording is much appreciated:

- transparent - public software must be visible and accessible to everyone
- accountable - it must be clear who is responsible for governing public software and how governance is implemented.
- understandable for its constituents - It must be clear what purpose, function and value public software has for its constituents

**Comment by ericherman** [comment]
Let's close this. If someone wishes to propose some sharper wording that would improve the introduction, we can re-open this issue.
