### ISSUE TITLE
Provide a definition of the core values in the context of public code

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/standard#318]
I'd like to report an issue in `introduction.md`

The standard considers public code to have these core values:

-  Inclusive
-  Usable
-  Open
-  Legible
-  Accountable
-  Accessible
-  Sustainable

I think it would be valuable to have a small definition of each of these values because they are core values. So what does it mean when public code is inclusive, or usable, open, sustainable. It might even be an idea to provide a separate section to elaborate a bit more on these core values as the define the value of public software. 

In this section we could for each value describe "What do we believe an inclusive public code to be" and "How can a codebase demonstrate it is inclusive" We could add pointers to a number of criteria which might touch upon these values.  Added bonus is that we get a value based entry point into the standard.

I can make a proposal

**Comment by Ainali** [comment]
Similarly to #317 (and [this comment](https://github.com/publiccodenet/standard/issues/317#issuecomment-1184452978)), I think this is meant to be general, but let's review this again after the summer to see if there are any new thoughts, or else we will close this issue.

**Comment by ericherman** [comment]
Let's close this. If someone wishes to propose some sharper wording that would improve the introduction, we can re-open this issue.

**Comment by ericherman** [comment]
incorporate this in https://github.com/publiccodenet/standard/issues/216
