### ISSUE TITLE
Style: bullets vs full sentences under headings?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#32]
We currently have ideas as bullets with no lead-in sentence under the templated subheadings. 

Proposal:
Resolve if this is our style, or if we'll always require gramatically correct lead in sentences.
(Context: 'What this does' under 'Create reusable and portable code bases' has a really long sentence that would be great as a bulleted list, but I don't want to create nested bullets for clarity reasons.

The sentence: 
Enables other policy makers, developers and designers to:

- reuse what you've developed
- test it
- improve it
- contribute those improvements back leading to better quality, cheaper maintainability and higher reliability

**Comment by ElenaFdR** [comment]
(The GDS style guide is very prescriptive about bullets: https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bullet-points-steps)

**Comment by ElenaFdR** [comment]
Further thesis: on a page where every single line starts with a bullet, the bullet becomes entirely meaningless. We could delete all of them.

**Comment by clausmullie** [comment]
True, but bullets does help speed skimming. Particularly if you are actively auditing, it's good to quickly see that to implement a particular requirement there are 3 bullets = 3 things to check. 

without bullets does it become less clear on what is a point that needs action?

**Comment by bvhme** [comment]
I would also say, if they are different items with no hierarchical connection to each other then they should be in bullets.

**Comment by Ainali** [comment]
Adding another perspective on this, it is probably useful to be able to refer to the requirements by an ID. This make it both easy and clear when referring to the requirement in text from anywhere (perhaps also with a link if we anchor each requirement). If we do, then this ID could be used instead of bullet points at the start of each line.

**Comment by bvhme** [comment]
We did consider this already a few times but have avoided it as we think this ID will likely change ahead of version 1.0.0.

If we introduce IDs they will be used which will make it prohibitively hard to switch around, add or remove criteria and requirements. Unless a non-lineair system is chosen (which seems like a sub-optimal idea, but perhaps necessary).

I recommend leaving IDs until we reach a more definite version.

**Comment by Ainali** [comment]
Sure, this is not the right time to introduce them, but if we have it on the roadmap for 1.0.0 then at least we can take part of the document aside from this discussion. Maybe this should be broken out as a separate issue for the backlog for now?

**Comment by ericherman** [comment]
Has this been sufficiently addressed by commit d040a8d62c0a112d69114429de472438c571d6e2 and other consistency oriented commits (e.g. 25b03b7d4fcfe9e17d22d9235d40105f994c2c64)?

**Comment by Ainali** [comment]
Yes, I believe so.
