### ISSUE TITLE
Basic navigation on standard.publiccode.net

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/standard#322]
When reading the standard a thing I was missing a bit was navigation. I noticed breadcrumbs are enable in the yaml configuration file of the standard and it is using the remote  https://github.com/publiccodenet/jekyll-theme.git but they are not active on standard.publiccode.net 

It would be nice to have a "next " and "previous" button and/or have a table of contents which shows 2 levels so you can quickly jump in out.  You would probably want to configure something so that generating the PDF would not include a web specific navigation.

**Comment by bvhme** [comment]
Yeah, I think the change to the `_config.yml` was made before the last release, so it'll be fixed in the next :)

And yes, a good and uniform way of dealing with navigation without creating extra overhead is an interesting challenge.

**Comment by felixfaassen** [comment]
I'll close this issue as  there is already a solution ;-)
