### ISSUE TITLE
Haromonizing requirements of use

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#323]
The criteria [Create reusable and portable code](https://standard.publiccode.net/criteria/reusable-and-portable-codebases.html) has a requirement:

> The codebase MUST be in use by multiple parties.

whereas the criteria [Pay attention to codebase maturity](https://standard.publiccode.net/criteria/advertise-maturity.html) states: 

>A codebase that is not yet ready to use MUST have one of these labels: [list]

If the first is met, the second is not really applicable. If the second is met, the first is failed. We should harmonize this in some way so that it becomes less contradictory/redundant.

**Comment by bvhme** [comment]
A codebase that is a prototype/alpha/beta (not ready to use in production) can defientely be used by multiple parties for instance in testing environments, but that might need some more clarification. What do you think @ericherman, how could we clarify this.

**Comment by ericherman** [comment]
I'm not sure I see the inconsistency as sharply. A codebase in incubation, one less than mature, could already be in use by multiple parties, provided that the parties -- I expect we'll see an example of this in the near future with one of the codebases we are helping.

When the "in use by multiple  parties" requirement was added, it was done so to clarify that software which is in use by only a single site would be FOSS, but not really fit into the scope of Public Code, with a community spanning multiple public bodies.

That said, perhaps it would be better add "a mature codebase MUST be in use by multiple parties", or convert from MUST to SHOULD.

**Comment by Ainali** [comment]
@ericherman I was not referring to our internal labeling of maturity (incubation, mature, attic) but to the phases in [Pay attention to codebase maturity](https://standard.publiccode.net/criteria/advertise-maturity.html) (prototype, alpha, beta, pre-release). E.g. if something is in alpha and thus _defined_ as not ready to use per that criterion, then it cannot be used by multiple parties. If it can, then our definition is clearly wrong.

**Comment by bvhme** [comment]
I think you're right. We don't have a consistent use of the word 'use' in use.

**Comment by ericherman** [comment]
@Ainali I understood it to be codebase maturity, as well. I apologize for making the topic murkier by trying to zoom out and paint a picture of software deployed and in use by multiple parties, yet still labeled as alpha or beta.

**Comment by Ainali** [comment]
Thanks to #346 the urgency is gone and I believe we can close this issue.
