### ISSUE TITLE
Term "Policy" or "Public Policy"

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/standard#325]
I noticed policy is used as a term quit a lot. Not be nitpicking about this terminology however as a technical person when reading the term in the context of bundle policy with source code the first thing in my mind was that policy is referring to policies one might have in place in order to do work. e.g. Policies about testing, code reviews etc.

If valuable we could maybe refer to "public policy" instead of "policy" as this is a standard I think definitions should be unambiguous as much as possible. Policy is a more broad term and I think we want to refer specifically to public policy.

two options:

1. we could add the word "policy" to the glossary and provide the "public policy" definition see https://en.wikipedia.org/wiki/Public_policy and Policy https://en.wikipedia.org/wiki/Policy
2. we could replace the word "policy" in the standard to "public policy" 

It think option 1 is the most effective

**Comment by ericherman** [comment]
Glossary entry seems like the better idea to me as well.

**Comment by bvhme** [comment]
And not to go all abstract here, but we definetely think both public policy and the other policy need to be bundled if reuse is intended and contributions are open.

**Comment by felixfaassen** [comment]
added a  proposal in pull request #329
