### ISSUE TITLE
Code of conduct could cater to public organizations better

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#330]
Most of the contributors to the Standard are professionals in the public field, for this reason, they already have certain professionalism being bound by codes of conduct of their organizations. Our current code of conduct also is written in a language and has goals that serve volunteer based projects better.

This would also fix #331.

**Comment by ericherman** [comment]
Would a code-of-conduct similar to https://docs.fedoraproject.org/en-US/project/code-of-conduct/ cater to public organizations better?

**Comment by Ainali** [comment]
> Would a code-of-conduct similar to https://docs.fedoraproject.org/en-US/project/code-of-conduct/ cater to public organizations better?

I really like this one. It's brief, but still clear, and it also has a straightforward tone that I believe would be fitting for our community.

**Comment by ericherman** [comment]
see also: https://llvm.org/docs/CodeOfConduct.html or the slightly more verbose https://www.djangoproject.com/conduct/

**Comment by ericherman** [comment]
The [Arch Linux CoC](https://gitlab.archlinux.org/archlinux/service-agreements/-/blob/master/code-of-conduct.md?rdfrom=https%3A%2F%2Fwiki.archlinux.org%2Findex.php%3Ftitle%3DCode_of_conduct) speaks to general concepts of respect, legality, correctness, and freedom before continuing on to talk about specific fora guidelines. While it is way too verbose, and dives into many things specific to the community and their work, the intros to each may be worth considering -- although the "freedom" section struck me as "out-of-tune" with what might best cater to public orgs.

**Comment by Ainali** [comment]
A work session for this is being planned for 4 July, react with :rocket: if you want to be invited.

**Comment by ericherman** [comment]
An older version of the [Fedora CoC](http://web.archive.org/web/20141031235644/http://fedoraproject.org/code-of-conduct) is much shorter
