### ISSUE TITLE
Security issues medium

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#339]
I'd like to report an issue in `criteria/open-to-contributions.md` which has a requirement:

> The codebase MUST include an email address for security issues and responsible disclosure.

Edo Plantinga reports that a more secure medium like a secured web-form might be better than email in some or many cases.

Perhaps this requirement should not mention the technology.

Reported by @EdoPlantinga.

**Comment by Ainali** [comment]
I think this is a great observation, and I like the direction of your suggestion. How about:

> The codebase MUST include instructions for how to privately report security issues and do responsible disclosure.

**Comment by Ainali** [comment]
fixed by #415
