### ISSUE TITLE
Create reusable code: clarity in language

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#34]
1. Does:
"## Policy makers: what you need to do

* Develop policy that is well documented and can be understood separate from the context"

mean that the policy can be understood separately from its context, or that the documentation is clear enough to be understood outside of its context? (The latter seems more specific and achievable to me).

2. Is this a correct reformulation of these sentences (under 'measure')?

Original:
* The codebase MUST enable others to submit suggestions for changes to the codebase from anyone and link to it from the documentation
* The codebase MUST have a public issue tracker that allows suggestions from anyone and link to it from the documentation

Proposed change:
* The codebase MUST have a public issue tracker that allows suggestions from anyone.
* The codebase MUST allow anyone to submit suggestions for changes to the codebase.
* The documentation must link to both the public issue tracker and submitted codebase changes.

**Comment by bvhme** [comment]
1. The documentation is clear enough to be understood outside of its context
1. Proposed changes seem good.

**Comment by ElenaFdR** [comment]
Spotted an error in my issue: change 2 refers to 'be open to contributions', not 'create reusable code'.

**Comment by bvhme** [comment]
Do you need something from me on that @elenafdr?

**Comment by ElenaFdR** [comment]
Just to approve my pull request :)
