### ISSUE TITLE
The index mentions the Standard is for Cities

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#340]
In the CodeForNL Slack the argument has been made the standard wouldn't apply to all public code because the index mentions "The Standard for Public Code gives cities a model for building their own open source solutions".

**Comment by ericherman** [comment]
Indeed, wording should be adjusted to indicate "public bodies such as cities" or similar. Good catch.

**Comment by bvhme** [comment]
I think there might even be an argument to be made here for either removing the sole example or make it multiple examples. I'm afraid it might stay confusing with just one example.
