### ISSUE TITLE
Consider splitting large requirements to smaller ones

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#343]
In [the last community call](https://blog.publiccode.net/community%20call/2020/06/22/notes-from-community-call-3-june-2020.html) we identified that some of the need for deep linking possibly could be met by splitting the criteria with most requirements into two new ones. The two one that we talked about was [Welcome contributions](https://standard.publiccode.net/criteria/open-to-contributions.html) and [Require review of contributions](https://standard.publiccode.net/criteria/require-review.html). Investigate if they meaningfully could be split into other parts.

Investigation:
- [x] Welcome contributions
- [ ] Require review of contributions

**Comment by ericherman** [comment]
@Ainali and @ericherman examined "Require review of contributions" and saw a potential division between exepectations of contributors and requirements of reviewers. However, as these two are closely interlinked, splitting these would not be an obvious improvement.

Closing for the time being, though future suggestions are welcome.
