### ISSUE TITLE
Higher level navigational layer to help contributors locate codebases

### ISSUE THREAD

**Issue by smuemd** [publiccodenet/standard#345]
Hello,

I came here via [https://about.publiccode.net/contributor-guides/for-individuals.html](https://about.publiccode.net/contributor-guides/for-individuals.html).

This is a very interesting project. Might very well be instrumental in improving how public software will be developed an procured in the future. This is exiting. (Do you have a newsletter or something equivalent? Would love to stay in the loop)

Having looked the contents of you web site, reminded me of some of the approaches to open organisations and development that I recently witnessed with some projects in the blockchain space. Specifically, I am thinking of [Protocol Labs](https://protocol.ai/), [Parity Technologies](https://www.parity.io/) and [Tlon / Urbit](https://urbit.org/) who pride themselves to operate and develop in the open. Hence browsing the repositories in their sprawling github organisations might be an illuminating exercise for you project:
- https://github.com/paritytech
  - https://github.com/parity-js
- https://github.com/protocol
  - https://github.com/ipfs
  - https://github.com/ipfs-shipyard
  - https://github.com/filecoin-project
  - https://github.com/libp2p
  - https://github.com/ipld
  - https://github.com/multiformats
- https://github.com/urbit

Two issues with these are immediately obvious:

**(1) ovent overextended, under-documented, and unfinished constellation of projects.**
No single part of these ecosystems is truly finished and well-documented, and new parts are spawned every day.

**(2) Excessive Jargon**
Likewise there often is a sprawling set of jargon that’s inconsistently used. Naming things is hard. There seems to be a need to standardize usage and meaning, and cull unnecessary jargon. (Jargon should be treated like technical debt)

It feels like this kind overarching organisational complexity makes these overly difficult to navigate. This is something I would anticipate to become an issue with code bases of public organisation over time as well. Well crafted READMEs, and `__START_HERE__` guiding repositories may help. Overall, I feel there needs to be a higher level navigational layer to help contributors locate codebases conceptually and understand how they relate to each other as well as to the overall roadmap of an org (in terms of a codebases lifecycle); also for the non-code side of things like project managment, areas of focus / priorisation and upfront design, scoping and engineering of constraints. These might be interesting aspects to consider when evolving the public code standard down the line. (I like your notion of code 'stewardship' to maybe take care of such things.)

**Comment by Ainali** [comment]
And you can sign up to the newsletter here: https://forms.gle/gn7wR2Eaxbv5g1BF9

**Comment by ericherman** [comment]
We've taken care to have information here on GitHub as well as on http://publiccode.net and https://standard.publiccode.net/ to be presented as clearly and organized as simply as possible. Recently, we took another pass at updating and organizing our pages and repositories. This work will continue in the future.

As for excessive jargon, we are making continuous efforts to follow the Standard for Public Code's criteria to [Use plain English](https://standard.publiccode.net/criteria/understandable-english-first.html)

The aspects raised in this issue we try to take in consideration for guiding our own work as well as the repositories and communities that we steward.
