### ISSUE TITLE
"Reviewers MUST provide feedback on all decisions" lacks clarity of intent

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#349]
Requirement text is "Reviewers MUST provide feedback on all decisions made and the implementation in the review."

If this is intended to deny "Looks Good To Me" as a valid review, then this text is correct, however in that case I suggest a SHOULD rather than a MUST.

If the intent is to ensure feedback for any reasons that a reviewer may *reject* a review, then I am on-board with the MUST level of requirement and we should clarify the text to reflect that nuance.

**Comment by Ainali** [comment]
I agree with everything Eric says and would suggest that we clarify this requirement to applicable on rejections only.

**Comment by ElenaFdR** [comment]
What about: "Reviewers MUST provide feedback on all decisions to not merge proposed code"?
