### ISSUE TITLE
Link to auditing template

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#350]
Does it make sense to link to [the auditing template](https://about.publiccode.net/activities/codebase-auditing/review-template.html)  we created from somewhere in the Standard?

**Comment by bvhme** [comment]
It does, or perhaps it should be part of the standard.

**Comment by ericherman** [comment]
I would like us to consider if a paper-friendly version could be included (or even inserted) into the last couple of pages of the standard.

**Comment by ericherman** [comment]
We have plans to automate the generation of the template [About #1201](https://github.com/publiccodenet/about/issues/1201). Once that automation is done, then we should make the template generation a part of the release process, and upload the template as another artefact of the release just like the PDF.

**Comment by Ainali** [comment]
I suggest that since we now add the pdf to the release, this issue can be closed.
