### ISSUE TITLE
Distinguish the requirements of the "Create reusable and portable code" criterion

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#351]
What's the difference between:

 - The codebase MUST be developed to be reusable in different contexts.
 - Code SHOULD be general purpose and SHOULD be configurable.

**Comment by ericherman** [comment]
It seems that the key distinction is "configurable" in the second. If the intent is "the code is made context specific via configuration" then "general purpose and configurable" could be stated more clearly.

**Comment by bvhme** [comment]
That was the intent:

> The codebase MUST be developed to be reusable in different contexts.

Was meant to mean 'Code like you have others reusing it'. Whilst:

> Code SHOULD be general purpose and SHOULD be configurable.

Was meant more as: make your code so it adapts to contexts by configuration and the code can be used out of context.
