### ISSUE TITLE
Add a requirement to consider the ethics of your software

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#354]
Proposal:
Add a point to the standard requiring maintainers to have considered the ethical implications of their software.

Why: so we can in good conscience nominate the Standard as a [Digital Public Good](https://digitalpublicgoods.net/about/), confident the Standard will do no harm.

Additional content: 
- suggest that maintainers check what ethical obligations they have from their public organizations
- suggest that there are nice tools that maintainers could use, like [ODI's Data Ethics Canvas](https://theodi.org/article/data-ethics-canvas/), the [Ethical Explorer](https://ethicalexplorer.org/), or even that tweet with 3 questions for any developer of new tech (eg does it help an abuser harass their victim?)
- encourage maintainers publish their ethical deliberations/decisions in the codebase codementation

**Comment by Ainali** [comment]
My first hunch is that this could fit under either [Bundle policy and source code](https://standard.publiccode.net/criteria/bundle-policy-and-code.html) which actually talks about the policy being implemented or [Document your objectives](https://standard.publiccode.net/criteria/document-objectives.html) where one could focus on actually documenting such considerations. Possibly, it could also be under both.

**Comment by ericherman** [comment]
@Ainali - I agree with your hunch. Is this a "what does this mean" more than a new requirement? For much public code there would already be policy in effect addressing things like Equal Opportunity and such.

**Comment by Ainali** [comment]
Let's explore if a line under **Policy makers: what you need to do** in both criteria is clear enough. As you say, ploicy is probably already in place for this on a higher level.

**Comment by Ainali** [comment]
> * suggest that there are nice tools that maintainers could use, like [ODI's Data Ethics Canvas](https://theodi.org/article/data-ethics-canvas/), the [Ethical Explorer](https://ethicalexplorer.org/), or even that tweet with 3 questions for any developer of new tech (eg does it help an abuser harass their victim?)

Since we made #356 a small improvement, I'll create a new issue for improving the Further reading sections.
