### ISSUE TITLE
Create video about the Standard

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#355]
A five minute video for the [Creative Commons Virtual Global Summit](https://sched.co/efB3).

**Comment by 2045** [comment]
What kind of video are you thining off? Is there a 'playbook', or rough sketch of the imagined content?

**Comment by ElenaFdR** [comment]
Hi @2045! We pitched this as a lightning talk introduction to how to use the Standard to help guide inter-org collaboration on software for a non-technical audience. Our inspiration for the bulk of it is an inflight safety video (what are the features of the Standard criteria, and how do you use them?)
We're putting the finishing touches on it now, but it'll be live next week.
We're also hosting a [talk and workshop](https://ccglobalsummit2020virtual.sched.com/event/efB6/from-public-innovation-to-public-infrastructure-why-digitalization-needs-stewardship) on why the digital commons requires stewardship.

**Comment by ElenaFdR** [comment]
We'll add a link here when it's live.

**Comment by 2045** [comment]
Okay, thanks for the feedback. Since I'll be teaming up with Eric to make a vid, I was wondering.. ;) Look forward to see the result.

**Comment by ElenaFdR** [comment]
We've now [published the video on YouTube](https://www.youtube.com/watch?v=QWt6vB-cipE&list=PL_5ziu2gADmDcp_ER8x2rcT1HOBaIe5cl&index=1).
