### ISSUE TITLE
Should localization of user-interfaces be covered?

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#359]
Language selection is one of the most important ways software can be made more accessible by a wider number of citizens.

It may already be policy for software to be in multiple languages.

Should this be explicitly mentioned, perhaps in advice to policy makers of https://standard.publiccode.net/criteria/bundle-policy-and-code.html ?

**Comment by Ainali** [comment]
Is this mostly a duplicate of #277 ?

**Comment by ericherman** [comment]
Yes, this is a duplicate of #277; perhaps I made a typo when searching.
