### ISSUE TITLE
Add CC Global Summit video on the Standard to README

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#360]
And check if there's anywhere else it makes sense to [link to the video](https://www.youtube.com/watch?v=QWt6vB-cipE&list=PL_5ziu2gADmDcp_ER8x2rcT1HOBaIe5cl&index=1).

**Comment by Ainali** [comment]
It might nice to add in the Standard section on projects.publiccode.net as well.

**Comment by Ainali** [comment]
Would we like a thumbnail image to be the link or just a plain text link?

**Comment by bvhme** [comment]
Yes.

(I mean, both are fine! if you go with the image, can you use Google's hosted thumbnail?)

**Comment by Ainali** [comment]
> if you go with the image, can you use Google's hosted thumbnail?

It should be possible, let's find out :)
