### ISSUE TITLE
Add something about required skills in a codebase?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#362]
A couple of times recently we have had the question of skills required for participating to/maintaining a codebase. That is, what kind of skills are needed in a codebase to either be able to contribute to it, or for making sure it can collectively be sustainably maintained by the community. 

Should we add something to the Standard about this? Things they might do or possible even a MAY requirement. A possibility is that we develop some material on About and then just add that as further reading somewhere.

**Comment by Ainali** [comment]
After thinking more on this, I do think we could explore a MAY requirement in [Make contributing easy](https://standard.publiccode.net/criteria/make-contributing-easy.html). 

One of the tips we got of an initiative using this was https://openknowhow.org/

**Comment by ericherman** [comment]
The conclusion of discussions is that codebase stewardship includes helping a community ensure that critical skills for the codebase are present among the collaborators with some redundancy, however this does not make for a specific requirement.

If someone wishes to put forward a proposed text for a requirement along these lines, we can certainly re-open this issue.
