### ISSUE TITLE
Reviews of contributions within 2 business days lacks rationale and further reading

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#367]
I understand that this requirement was arrived at with a combination of experience, original research, and pre-existing research ... the Standard could include supporting information and rationale in "why this is important" and/or "further reading" sections.

**Comment by bvhme** [comment]
From a Mozilla presentation: https://docs.google.com/presentation/d/1hsJLv1ieSqtXBzd5YZusY-mB8e1VJzaeOmh8Q4VeMio/edit#slide=id.g43d857af8_0177

**Comment by ericherman** [comment]
Amsterdam guide "How we track Open Source health": https://amsterdam.github.io/guides/track-open-source-health/
