### ISSUE TITLE
Nice is not enough information on why a link is further reading

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#370]
In `criteria/make-contributing-easy.md` it states:

> * [Verdaccio's security policy](https://github.com/verdaccio/verdaccio/blob/master/SECURITY.md) is a really nice example.

This doesn't tell you anything about the example or why it's a good example, plus it is very subjective. Is it nice because of 'aestetic'?

I propose we add a bit about why it's nice.

**Comment by ericherman** [comment]
Perhaps we should use https://open-zaak.readthedocs.io/en/stable/support/security.html  as an example.

**Comment by Ainali** [comment]
Now that we have the Implementation guide, specifically made to highlight really nice examples, we should move this sentence there. We could still improve the sentence, but optimize it for the guide rather than for the Standard itself.
