### ISSUE TITLE
Helping people use our glossary (and better understand our worldview)

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#375]
Should we link to the glossary each time we use one of the terms we've specifically defined for the first time on a page?
Especially for common terms (eg code or general public) that we've defined very specifically, it might be helpful for users to have a signal that we have a specific definition.

**Comment by ElenaFdR** [comment]
As a follow up, are there implications for our print style sheet if we significantly increase the number of internal links?

**Comment by ericherman** [comment]
I believe internal, relative links and already skipped, thus we could add more links to the glossary without overly cluttering the printed version if we (Wikipedia style) link each term used once per page.
