### ISSUE TITLE
Monitor for broken links masked by ignored errors (HTTP 429)

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#382]
In our CI test script, we ignore 429 (too many requests) errors as these are not indicative of broken links, rather the result of a server seemingly treating or CI like it would a DoS bot.

We should monitor all links, including those that regularly return 429 in CI testing, in order to discover and report on problems hidden in testing.

**Comment by ericherman** [comment]
See: https://github.com/publiccodenet/standard/pull/380

**Comment by ericherman** [comment]
We can also consider the option of linking to archive.org if something is not reliably available.

e.g.:
http://web.archive.org/web/20201027095103if_/https://www.youtube.com/watch?v=QWt6vB-cipE&gl=US&hl=en

**Comment by Ainali** [comment]
> We can also consider the option of linking to archive.org if something is not reliably available.
> 
> e.g.:
> http://web.archive.org/web/20201027095103if_/https://www.youtube.com/watch?v=QWt6vB-cipE&gl=US&hl=en

Perhaps we should give some priority to #275 ?

**Comment by Ainali** [comment]
> We can also consider the option of linking to archive.org if something is not reliably available.
> 
> e.g.: http://web.archive.org/web/20201027095103if_/https://www.youtube.com/watch?v=QWt6vB-cipE&gl=US&hl=en

@ericherman Can we consider this solved for now with #642?

**Comment by ericherman** [comment]
fixed by: 6aab0ae6d0141bddb5ebff0aaee683531eda261c
