### ISSUE TITLE
Are policy makers or managers responsible for setting procurement policy?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#387]
We currently assume it's policy people, whereas I have the impression it's often a more political (and therefore more senior) decision. To hedge our bets, we could instruct both professions to support procurement of open source/open standards throughout the Standard.

The guidance for each group in 'Use open standards' is quite different, and seems inadequate re procurement.

**Comment by ElenaFdR** [comment]
This may also turn on a confusion we encountered when identifying audiences for the Foundation's [communications plan](https://about.publiccode.net/activities/communication/communications-plan.html): the difference between 'management' and 'leaders'. In the communications plan, we decided 'leaders' were more senior, and clarified management as 'middle management'.

**Comment by ElenaFdR** [comment]
The reader's guide makes our definitions of these roles quite clear - I suggest we methodically check all of our guidance against how we allocated responsibilities to make sure there are no gaps, and the efforts are fully complementary.

**Comment by Ainali** [comment]
> We currently assume it's policy people, whereas I have the impression it's often a more political (and therefore more senior) decision.

I don't follow you here. I thought we included politicians in Policy makers. If not, do we need to add a fourth group?

**Comment by ericherman** [comment]
Today, the guidance is for the policy makers to create policy about use and procurement. Regardless of who is doing the procurement, they should be following the policies.

We can re-open this issue, if someone wishes to reference it in a PR. Closing for now.
