### ISSUE TITLE
Odd reference to "Public Code" in 'Create reusable and portable code'

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#389]
This Public Code reference seems out of sync with how the Standard is currently used, especially since we [never agreed a labelling convention for mature codebases](https://github.com/publiccodenet/about/issues/223) stewarded by the Foundation for Public Code.

```
Codebases used by multiple parties have broad enough value to be Public Code and are more likely to benefit from a self-sustaining community.
```

Options:

- make it generic
- add a hyperlink or inline explanation

**Comment by Ainali** [comment]
I suggest just shortening it to:

> Codebases used by multiple parties are more likely to benefit from a self-sustaining community.

**Comment by ElenaFdR** [comment]
Nice suggestion, @ainali!
