### ISSUE TITLE
English first: Give policymakers the responsibility of explaining their policy without jargon

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#39]
Make them own explaining their work outside their specific legal/linguistic context.
They can also peer review each other's work, to ensure legibility.

**Comment by ElenaFdR** [comment]
Add links to plain English info (and the benefits of opening up, not dumbing down) in further reading.

**Comment by ericherman** [comment]
This work has been done.

Of course we could improve the wording, I'm sure, but for now, in https://github.com/publiccodenet/standard/blob/0.1.4/criteria/reusable-and-portable-codebases.md we have:

> Policy makers: what you need to do
>
>    Document your policy with enough clarity and detail that it can be understood outside of its original context.

And:

> Further reading
>
>    Making source code open and reusable by the UK Government Digital Service.
