### ISSUE TITLE
No branding allowed in codebase names?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#390]
In 'Use plain English', we say "The name of the project or codebase SHOULD be descriptive and free from acronyms, abbreviations, puns or branding". 
This is at odds with some of our best practice for codebase product marketing, which includes considering the uniqueness of a codebase's name (to avoid namespace conflicts and support findability/SEO).
I also wonder if this might alarm vendors who want assurance that a codebase they invest in is marketable.

**Comment by Ainali** [comment]
Good catch! As soon as a codebase have a name, obviously it will be branding in itself. I am thinking this is intended to have the name be free from *other* brands, like a company or city name.

**Comment by Ainali** [comment]
A few alternative suggestions that could follow and end the sentence "The name of the project or codebase SHOULD be descriptive and free from acronyms, abbreviations, puns or branding": 

* based on the name of any participating organization.
* based on the organization that started the codebase.

**Comment by Ainali** [comment]
Fixed by #518
