### ISSUE TITLE
Update URL of 'Use Plain English'

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#392]
The URL is currently 'understandable-english-first'. 
For building trust, it's useful if the URL is human readable, and the H1 is sufficiently similar (or identical) that a user has immediate confirmation they've landed where they expected to when they clicked on the hyperlink.

**Comment by ericherman** [comment]
There are a few of these throughout the repo. I suggest we review them all and ```git mv``` them one by one.

**Comment by Ainali** [comment]
If we move them, we must make sure to remember to create redirects for the old URLs.
