### ISSUE TITLE
Make awkward sentence easier to understand

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#395]
This sentence from the reader's guide is flagged as 'very hard to read' by Hemingway.

"In order to limit ambiguity, the key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [IETF RFC 2119](https://tools.ietf.org/html/rfc2119)."

**Comment by ericherman** [comment]
I suggest we drop the "In order to limit ambiguity" clause and follow [RFC 2119](https://tools.ietf.org/html/rfc2119), which states:

```
    Authors who follow these guidelines should incorporate this phrase near the beginning of their document:

      The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
      NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
      "OPTIONAL" in this document are to be interpreted as described in
      RFC 2119.
```

**Comment by Ainali** [comment]
Another way of structuring it that might be easier to parse is to make a list. Perhaps something like:

> In order to limit ambiguity, the following key words in this document are to be > interpreted as described in [IETF RFC 2119](https://tools.ietf.org/html/rfc2119): 
> - MUST 
> - MUST NOT
> - REQUIRED
> - SHALL
> - SHALL NOT
> - SHOULD
> - SHOULD NOT
> - RECOMMENDED
> - MAY
> - OPTIONAL

**Comment by bvhme** [comment]
If only I had documented why I added 'in order to limit ambiguity' on Apr 15, 2019. Reverting to the way it's described in the RFC has my preference.

**Comment by Ainali** [comment]
> I suggest we drop the "In order to limit ambiguity" clause and follow [RFC 2119](https://tools.ietf.org/html/rfc2119), which states:
> 
> ```
>     Authors who follow these guidelines should incorporate this phrase near the beginning of their document:
> 
>       The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
>       NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
>       "OPTIONAL" in this document are to be interpreted as described in
>       RFC 2119.
> ```

Hemingway still believes this sentence is _very hard_ to read with a Readability grade 15. The bullet point is "only" _hard_ to read with a Readability grade 3.
