### ISSUE TITLE
Remove sections on how the Foundation uses the Standard from the introduction

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#396]
Replace these with a statement of the Standard's importance to our mission and practice, add a hyperlink to About or marketing materials for what we offer and how we use the Standard.

Why: 
- the current text was written before we had codebases in incubation, and doesn't reflect what we know now about codebase stewardship
- the Standard will be easier to use by a wider range of actors (not all of whom may be interested in our stewardship) without these paragraphs
- removing our obsolete process description from the Standard reduces future content debt - it means we have fewer, better focused places to keep our process description accurate, and allows the Standard intro to act primarily as rhetoric (a call to arms)
- making this text shorter but better makes translation/maintaining translation easier and cheaper

**Comment by Ainali** [comment]
Work session planned to 18/1 - react with a 🚀 if you want an invitation.

**Comment by Ainali** [comment]
The sections about how we use it and the certification were recently added to publiccode.net, see publiccodenet/publiccode.net#260
