### ISSUE TITLE
Standardize 'advertise' vs 'advertize'

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#400]
We currently use both in the Standard, which isn't ideal but doesn't impede understanding.

**Comment by Ainali** [comment]
Which one do we prefer?

**Comment by bvhme** [comment]
I expect we prefer 'advertise' as I think it's probably the British version, however @ElenaFdR has a much better handle on this than me.

**Comment by bvhme** [comment]
@Ainali mentioned we're doing American and I think he's right! So 'Advertize' it is.

**Comment by ElenaFdR** [comment]
Yes, we're doing American. But the internet reckons advertise is right: see [Grammarist](https://grammarist.com/spelling/advertise-vs-advertize/) and [StackExchange](https://english.stackexchange.com/questions/341707/should-advertised-be-spelled-with-a-z-in-american-english).

**Comment by Ainali** [comment]
So let's go for *advertise*?
