### ISSUE TITLE
New line in the middle of the phone number

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#401]
The phone number in [print.html](https://github.com/publiccodenet/standard/blob/develop/print.html) should get non-breaking spaces to prevent it from getting a line break in the middle of it (as it does in the [v 0.2.0 pdf](https://github.com/publiccodenet/standard/releases/tag/0.2.0)).

**Comment by ericherman** [comment]
Martin @2045, this cold be a good candidate for your how-to.

**Comment by 2045** [comment]
@ericherman yes, this will work, I think, so I'll prep for the complete cycle, have to get the vid man onboard. I'll get back to you, and let's leave this one for this purpose.

**Comment by Ainali** [comment]
Work session planned to 18/1 - react with a 🚀 if you want an invitation.

**Comment by ericherman** [comment]
This appears to have been fixed (coincidentally) by d9d75e5e32de32a405e48d9de86ff7cc48b8b70b
