### ISSUE TITLE
Words with line break but without hyphen

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#402]
[On page 51 in the pdf of v.0.2.0](https://github.com/publiccodenet/standard/releases/download/0.2.0/standard-for-public-code-0.2.0.pdf) two words got line breaks in them without a hyphen. See if it possible to either skip the line break with a no-wrap or force a nice line break with a hyphen.

**Comment by ericherman** [comment]
https://github.com/publiccodenet/standard/issues/391 invites us to re-write the sentences, which might side-step the issue.
