### ISSUE TITLE
Source retrieved 6 years ago?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#403]
In the [glossary](https://github.com/publiccodenet/standard/blob/develop/glossary.md), we state that the source for Version control was retrieved 6 years ago. Did we actually retrieve it back then and kept in memory until now, or is this a [copy and paste error](https://en.wikipedia.org/wiki/Continuous_integration#cite_note-martinfowler-1)?

**Comment by felixfaassen** [comment]
it is an exact copy past of the original source / reference description stated on Wikipeda. For clarity we could remove the dates and just state the source.
