### ISSUE TITLE
Document and script PDF cover generation

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#405]
Currently the process a bit manual and usually done by one person. Let's document the process so more people can do it, and hopefully we can also automate the job so we can streamline the release process.

**Comment by felixfaassen** [comment]
Maybe too much for now we could also look into automating this. PDF Jekyll is a plugin which can facilitate this: https://github.com/abemedia/jekyll-pdf

**Comment by bvhme** [comment]
Right now the cover is plucked out of Figma. If we want to generate it the same way I think it's best to make a separate HTML for the cover (a bit larger than A3 with the spine and bleed).

**Comment by Ainali** [comment]
Now when the cover is included in the "regular" pdf, perhaps the instructions need to be updated? How would the sending to the printers process be affected by this? If we just use the same process with the  new files we will kind of get double covers on the printed version.

**Comment by Ainali** [comment]
Closed with #562
