### ISSUE TITLE
Changed URL without redirect

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#407]
As discovered in publiccodenet/about#777 when the criterion Advertise you maturity changed name to Document codebase maturity in #311 the URL changed but no redirect was created, making external links broken. We should create a redirect so that this change does not break external links to this criterion.

**Comment by bvhme** [comment]
Do we think this should be a [hotfix](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)?

**Comment by ericherman** [comment]
7671db348ad391a134c97223573d8a0fc31b6f9e
