### ISSUE TITLE
Standard lacks guidance for "rolling release" environments

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#419]
Versioning as described in criteria/document-maturity.md and criteria/version-control-and-history.md is clear for packaged software and APIs, but a little less clear for codebases which have a rolling-release process especially where the updates tend to involve regular content changes or evolving layout with A/B testing.

Even if the criteria requirements are sufficient, the guidance for these environments is thin.

**Comment by Ainali** [comment]
[This is an example](https://poit.bolagsverket.se/poit/PublikStartIn.do) of a government site which _might_ be best suited to rolling releases since it is for public service announcements.

**Comment by ElenaFdR** [comment]
@Ainali I'd expect rolling content changes to be handled by a CMS, not in the code.

**Comment by raboof** [comment]
> @Ainali I'd expect rolling content changes to be handled by a CMS, not in the code.

While a CMS is a fine tool for rolling content changes, using a version control system (and a 'continuous delivery' pipeline to let changes flow to production, for example with a static site generator like jekyll or hugo) is also a great approach.

Also for projects (less so for libraries) I think this is a valid approach. I still think, even if artifacts are produced for each merge to master, those artifacts should be versioned somehow. Perhaps we should just clarify that it's OK if versions are derived from the version control system metadata (like git-describe) - something like #421?

**Comment by ericherman** [comment]
Resolved: https://github.com/publiccodenet/standard/pull/421
