### ISSUE TITLE
Introduction: add project plan and workshop reports 

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#42]
Take the rationale from the both the Smart Cities Public Code paper as well as the workshop reports and integrate it into the introduction

**Comment by ElenaFdR** [comment]
How long should the introduction to be?

**Comment by bvhme** [comment]
All of the content we've made until now is in this repository

https://github.com/publiccodenet/smart-cities-public-code/

I think the length of the introduction doesn't matter as much, as long as it touches on all the points that are now in the outline.

**Comment by clausmullie** [comment]
fixed with #101
