### ISSUE TITLE
Add further reading to 'make contributing easy'

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#428]
Specifically the study that shows that people with a positive first contributing experience are more likely to contribute again in the future.

**Comment by Ainali** [comment]
@ElenaFdR do you know which study this was?

**Comment by Ainali** [comment]
> Is this done already?
> 
> * [Measuring Engagement](https://docs.google.com/presentation/d/1hsJLv1ieSqtXBzd5YZusY-mB8e1VJzaeOmh8Q4VeMio/edit#slide=id.g43d857af8_0177) by Mozilla.

Well, that link is in Require review of contributions. It sort of makes sense there too, as it shows the effects of quick reviews. Do we want it twice, or should we just have it over there?

**Comment by ericherman** [comment]
I don't think twice is great, but maybe.
Maybe it should move to here.

Or perhaps point the reader to the other section, maybe something along the lines of a summary statement suggesting that this topic is also covered in the [other criterion].

**Comment by Ainali** [comment]
In the "Developers and designers: what you need to do" sections on both criteria, we do talk about responding promptly. Should we just add something like: "Just like for [reviews](require-reviews-of-contributions.md#developers-and-designers-what-you-need-to-do), make sure to respond to requests promptly"?
