### ISSUE TITLE
Contributor funnel as further reading

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#436]
I found the nice text: [The Open Source Contributor Funnel (or: Why People Don’t Contribute To Your Open Source Project)](https://mikemcquaid.com/2018/08/14/the-open-source-contributor-funnel-why-people-dont-contribute-to-your-open-source-project/) that I think would be a good Further reading to [Welcome contributors](https://standard.publiccode.net/criteria/open-to-contributions.html). However, the criteria already has five good links, would it be overloading it?

**Comment by ericherman** [comment]
Here's a thought: while there is no specific limit, perhaps it is useful to imagine for a moment that there is one. Is another one of the links less valuable than this one? If so, I'd say add this one anyway, and separately raise the question of the value of the other links.

**Comment by Ainali** [comment]
Good point. I think this one is more valuable for the criteria as a whole than the link to the contributor covenant, which is just an example of a MAY requirement. A better link for that one would be someone that talked about code of conducts in general, perhaps with advice of what to think of when picking one. That one is more of an example, which relates to #162.
