### ISSUE TITLE
Style: standardise what we call the 15 points/criteria in the standard.

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#44]
I suggest 'points' for simplicity (GDS does this - see https://www.gov.uk/service-manual/service-standard/understand-user-needs).
OSI call them 'criteria' (see https://opensource.org/osr)
Both pass the Google Translate test.

And then start using this in all of our discussion of the standard, so that we consistently set people's expectations.

**Comment by bvhme** [comment]
As I get it, on the home page of the Service Manual it is called the '[18 criteria](https://www.gov.uk/service-manual/service-standard)' or am I reading it wrong?

**Comment by ElenaFdR** [comment]
Suggest we move this:
- out of the standard project (since, with the exception of the introduction, we refer to the standard points more outside of the standard)
- away from this milestone

**Comment by bvhme** [comment]
Hmm, I don't know if I understand, is the question 'what do we call one of the 14 standards'?

I feel like this:

- 1 Standard (entire document)
- 14 Points (the seperate 'standards')
- Each with their own Criteria

What do you think @ElenaFdR, seems like a straightforward change.

**Comment by ElenaFdR** [comment]
Yup, this sounds good.

**Comment by bvhme** [comment]
There has been a bit more thinking, looking at other standards and the dictionary and I feel that for the lowest level 'requirements' might be more explicit.

I think

* 1 standard: to indicate that this is the norm
* 14 criteria: the standard by which judgement occurs
* Each with their requirement: the things that are needed to fulfil those
