### ISSUE TITLE
Create version 0.2.1

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#444]
1. Review state of the 'develop' branch
    - [x] Ensure all changes intended for release are merged
    - [x] Invite a proofread of the current state of the branch
    - [x] Finish proofreading phase
2. Create a release branch
    - [x] From 'develop', `git checkout -b "release-$MAJOR.$MINOR.$PATCH"`
3. Update the new release
    - [x] Update version number in `_config.yml` and `README.md`
    - [x] Update [`AUTHORS.md`](AUTHORS.md) with new contributors
    - [x] Update [`CHANGELOG.md`](CHANGELOG.md)
    - [x] Perform extra pass on diff to the 'main' branch
        - [x] Reread any section or paragraph to ensure wording changes still fit the whole and do not contain grammar or spelling errors
        - [x] If needed, commit fixes and repeat extra pass
    - [x] Push branch, open a pull request to the 'main' branch
        - [x] Request review from multiple reviewers, especially a proofreader
        - [x] Reviewers will create issues for shortcomings found which would not prevent release
        - [x] If needed for release, reviewers may create PRs to resolve issues
        - [x] Re-request reviews if additional PRs are merged into release branch
    - [x] Generate new PDF of the primary content
        - [x] Serve html content with `script/serve.sh`
        - [x] Optionally, for a visual pre-check, navigate to http://127.0.0.1:4000/ in a browser
        - [x] Generate the pdf with `script/pdf.sh`
    - [x] Create new cover for print
    - [x] Create new cover for web PDF
    - [x] Create PDF for GitHub release with front and back cover included
        - [x] Generate the pdf with `pdftk Front.pdf standard.pdf Back.pdf cat output standard-for-public-code-$MAJOR.$MINOR.$PATCH.pdf`
4. Send the files for print to the printer
    - [x] Cover file
    - [x] Inside pages PDF
5. Create GitHub release with the release notes and version number
    - [x] `git tag $MAJOR.$MINOR.$PATCH`
    - [x] `git push --tags`
    - [x] from https://github.com/publiccodenet/standard/releases edit the tag
        - [x] Title the release
        - [x] Add changelog bullets
        - [x] Drag-and-drop the generated .pdf into the assets
6. Update 'develop' with a merge from 'main'

**Comment by Ainali** [comment]
I've done a full proofreading of the develop branch now and besides the possible more dashes to change I can't find anything more.

**Comment by bvhme** [comment]
[Cover back and front.pdf](https://github.com/publiccodenet/standard/files/6076919/Cover.back.and.front.9.pdf)
[Back.pdf](https://github.com/publiccodenet/standard/files/6076920/Back.6.pdf)
[Front.pdf](https://github.com/publiccodenet/standard/files/6076921/Front.7.pdf)

**Comment by Ainali** [comment]
Published to GitHub, https://github.com/publiccodenet/standard/releases/tag/0.2.1
only thing left is to do the actual printed copies.

**Comment by Ainali** [comment]
Prints was ordered earlier, closing this now.
