### ISSUE TITLE
Replace cagey references to "our organization" with the Foundation for Public Code

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#453]
These were added in [Version 0.1.1](https://github.com/publiccodenet/standard/blob/develop/CHANGELOG.md) so that we could release despite an ongoing debate about changing the Foundation for Public Code's name. Some of the references were quite contrived; reverting to "the Foundation for Public Code" would make the writing stronger in many cases.

**Comment by Ainali** [comment]
Agreed, [these three instances](https://github.com/publiccodenet/standard/search?q=%22our+organization%22) could be changed to "the Foundation for Public Code" and it would be an improvement.

**Comment by ericherman** [comment]
665e929f0c4bebea049915b2b096b44d52cc84a9
