### ISSUE TITLE
Remove colon

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#454]
From the Introduction, this is weirdly punctuated:

```
These people work at:
* public organizations: institutions and administrations
```

I also question whether this clarification is as helpful as it could be - it feels like it's missing the phrase 'public sector', while we know that a 'public organization' in the US can be mistaken for a publicly listed company.

**Comment by Ainali** [comment]
Would this be better?

>These people work at:
>* institutions, organizations and administrations in the public sector
