### ISSUE TITLE
Accessibility and equal opportunity policies are usually mandated by law, not "values and ethics"

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#461]
This advice to policy makers in 'Document your objectives':

> Include relevant polices which impact the community, codebase, and development like value and ethics based polices, for example accessibility or equal opportunity.

feels like it misses the point in 2 ways:
- people creating a codebase need to know about any legal obligations/constraints on their work (be they about accessibility or, say, data retention policies)
-  accessibility or equal opportunity policies that are applicable to a codebase are usually there because a group of activists spent decades fighting for recognition and protection; calling them "value and ethics based polices" feels like it trivializes their importance.

Solution: replace this bullet with:

> - Include relevant policies which impact the community, codebase, and development, including legal obligations like the [General Data Protection Regulation](https://eur-lex.europa.eu/eli/reg/2016/679/oj) or the [EU Web Accessibility Directive](https://ec.europa.eu/digital-single-market/en/web-accessibility), or human rights policies, like a public organization's commitment to equal opportunity.

Also, this should probably be in 'bundle policy and source code' instead of 'document your objectives'.

Thus my suggestion for policymakers in 'document your objectives' becomes:

> - Add links or references from your policy objectives to supporting policy documents added to meet the 'bundle policy and source code' criterion 

**Sidenote: there's a typo 2x on 'policies' - it currently says 'polices' 🚓🚓**

**Comment by ericherman** [comment]
Wait "polices"? Hah! Good catch @ElenaFdR 
That's a real bug, not a "nice to have; I'll get that much fixed before next release.

I like all of the rest of this, too, but should be a separate patch.

**Comment by mgifford** [comment]
Would hope that accessibility (like security & sustainability) were being built in and factored at every stage of the process. So much easier to address early on in the process.

**Comment by ericherman** [comment]
Indeed @mgifford

Explicitly documenting that these legal obligations and policies apply to the codebase should help it get attention from the early stages.

**Comment by Ainali** [comment]
@ElenaFdR  I think your suggestion is good. I would just tweak the last bullet point to:

>-  Make sure that all your codebase objectives have links or references to supporting policy documents added to meet the [Bundle policy and source code](https://standard.publiccode.net/criteria/bundle-policy-and-code.html) criterion.
