### ISSUE TITLE
Alpha/beta/live framework creeping obsolescence?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#467]
Mandated in 'Document codebase maturity'.
Keep an eye on replies to this tweet (and similar): 
https://twitter.com/richardjpope/status/1359225067666890760?s=20

**Comment by ericherman** [comment]
Six months have passed and no obvious traction for an alternative way to communicate codebase maturity, thus marking this for closing on or after 2021-09-30 if no additional input.
 
We can revisit the topic when a compelling alternative is put forward.

**Comment by Ainali** [comment]
Closed based on the previous comment and more than a year passing.
