### ISSUE TITLE
Add vendor and platform independence as a criterion

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#47]
Removed this standard in #46 since it was empty, it would be politically interesting to see if we want it back in

**Comment by ElenaFdR** [comment]
@bvhme @Ainali Could one of you add an explanation of the problem this is trying to solve ahead of next week's community call?

**Comment by ericherman** [comment]
My understanding is that this is about vendor lock-in. If vendors or service providers are required for a codebase, and we do not see that there are multiple vendors or service providers, then this brings into focus the risks related to that single vendor or provider.

For example, how much confidence can we have that installations will be able to migrate if the single provider shuts down? @bvhme @Ainali does this match your understanding?

**Comment by ericherman** [comment]
I question whether this is a whole new criterion or whether it is part of the requirement to create reusable and portable code, where we already find:

* The codebase SHOULD be in use by multiple parties.
* The roadmap SHOULD be influenced by the needs of multiple parties.

Is it enough to add a requirement along the lines of:

* Required services SHOULD be available by multiple vendors.

https://standard.publiccode.net/criteria/reusable-and-portable-codebases.html

**Comment by ericherman** [comment]
To each of the criteria which has requirements which promote vendor and platform independence, we could mention something in the "why this is important" sections.

**Comment by Ainali** [comment]
Notes from the last blog post where we discussed this: https://blog.publiccode.net/community%20call/2021/12/13/notes-from-community-call-2-december-2021.html

**Comment by ericherman** [comment]
Would it be more clear to make it a SHOULD NOT? Perhaps:

* The code SHOULD NOT require services or platforms available from only a single vendor.

**Comment by Ainali** [comment]
I think this is in the right direction, but perhaps it is too narrow? I can imagine a scenario where the services or platforms are only available from a single vendor *today*, which, of course, could be fine. What wouldn't be fine, is if they have some sort of monopoly. The wording for that nuance is non-trivial, though.

**Comment by jgroenen** [comment]
Maybe somethinglike: the code SHOULD NOT depend on proprietary code or services
...to be able to use it, understand it, modify it, configure it, distribute it, (https://www.gnu.org/philosophy/free-sw.html)

Maybe explicitly name some vendor lock-ins to be aware of (even if the code itself is open source): runs only on proprietary infrastructure, requires not publicly available knowledge to understand what's happening, requires non-free integrated services?

**Comment by ericherman** [comment]
@jgroenen the code angle of the SHOULD NOT that you propose is covered by another criterion, but the services is a gap, your phrasing really "zeros-in" the lock-in aspect, maybe that's more clear.

The explicitly naming I think sits betting in the implementation guide rather than direct "what you need to do" guidance or further reading.
