### ISSUE TITLE
Language tweaks to Code of Conduct

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#472]
Replace 'making' with 'make':
>In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

Replace 'that is deemed' with 'we consider':
> All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances.

**Comment by ericherman** [comment]
Perhaps side-stepped by issue #398 "Update Code of Conduct"
