### ISSUE TITLE
Should the title "Document your objectives" change?

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#489]
In [issue 57](https://github.com/publiccodenet/standard/issues/57) we changed most uses of "your codebase" to "the codebase". Now the criterion title is not well aligned with the content:

# Document your objectives                                                      
                                                                                
## Requirements                                                                 
                                                                                
* The codebase MUST contain documentation of its objectives – like a mission and goal statement – that is understandable by designers and developers so that they can use or contribute to the codebase.
* The codebase SHOULD contain documentation of its objectives understandable by policy makers and management.
* The codebase MAY contain documentation of its objectives for the general public.

**Comment by ericherman** [comment]
Any thoughts? @ElenaFdR @Ainali @bvhme .... I lean towards changing the title to "Document codebase objectives" ....

... and also, I think the "what you need to do" sections could be expanded a bit, but that should be a separate issue.

**Comment by Ainali** [comment]
Nice find! Yes, it does make sense. Alternatives are the long form "Document the objectives of the codebase", or the very short, "Document the objectives". But I think your proposal is better than both of these.

**Comment by ericherman** [comment]
e5c32a128b380272185d06b08d7978cdf99a314f
