### ISSUE TITLE
Ensure consistency in where we use 'SHOULD', 'COULD' and 'MUST'

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/standard#49]
We always use it in measure, but only sometimes in like 'what developers should use' (ie see standards/bundle-policy-and-code.md).

Perhaps only leave it in the measure section?

**Comment by ElenaFdR** [comment]
Using this only in 'measure' makes sense to me.

**Comment by ElenaFdR** [comment]
Source material? https://tools.ietf.org/html/rfc2119
