### ISSUE TITLE
For unavoidable legal/domain specific terms, setup a glossary

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#492]
After a chat with @CoNaana, an insight is that in municipal context it can 1) be very hard to avoid legal/domain specific terms and, 2) it can be hard to get everyone in the same codebase to use them consistently. 

Hence, what management need to do could possibly be extended with advice that all legal/domain specific terms that *are* used should be added to a codebase glossary that clearly explains what they mean in this specific context.

**Comment by marcvanandel** [comment]
Should translations be part of the glossary as well? Because local context and local laws define the domain at hand I expect the glossary to follow the domain ... but interoperability and inclusion should not be bound to the local language ... or should it?

**Comment by Ainali** [comment]
> Should translations be part of the glossary as well? Because local context and local laws define the domain at hand I expect the glossary to follow the domain ... but interoperability and inclusion should not be bound to the local language ... or should it?

Yes, I think those should be part of it. We have this requirement in [Use plain English](https://standard.publiccode.net/criteria/understandable-english-first.html):

> There SHOULD be no acronyms, abbreviations, puns or legal/non-English/domain specific terms in the codebase without an explanation preceding it or a link to an explanation.

So both unavoidable legal/domain specific terms and non-English terms are in the same conversation here. And I think that it would be good to have all these in a glossary so that they are less likely to be interpreted in different ways by different community members.

**Comment by marcvanandel** [comment]
This is getting close to the meaning of words and the understanding of words. This is why Domain Driven Design emphasizes a [ubiquitous language](https://thedomaindrivendesign.io/developing-the-ubiquitous-language/). A glossary is part of the 'solution' but also the notion of the domain or context. This might be relevant for the Standard as well. Words might be used in other context but what do they mean in the context (domain) of the Standard?

**Comment by Ainali** [comment]
> Words might be used in other context but what do they mean in the context (domain) of the Standard?

The domain should be understood as the codebase at hand. (A codebase is not developed in the context of the Standard.) Or am I missing your point?

**Comment by marcvanandel** [comment]
Half of it. It meant that the Standard itself needs a glossary as well as the codebase at hand 😉 And it should be clear for each word in the codebase at hand which glossary it refers to, especially if words are used in both glossaries!

**Comment by Ainali** [comment]
The Standard for Public Code [has a glossary](https://standard.publiccode.net/glossary.html). 😀
And yes, I agree it much be clear. That's why I suggest linking to the appropriate glossary when using one of the terms.
