### ISSUE TITLE
Document Codebase Maturity lacks reference to the Standard itself.

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#493]
Document Codebase Maturity could provide guidance regarding maturity labeling relative to the standard itself.

If a codebase is moving from the Alpha to the Beta phase, are there criteria which would be expected to already be met?

Are there criteria, or requirements, in earlier phases which would naturally be less likely to be met?
For example:
 * It may not be possible to create complete documentation of a prototype feature until the feature is more complete.
 * How confident would we be that a codebase is reusable in multiple contexts before it's proven usable in the first context?

**Comment by ericherman** [comment]
Thanks @jgroenen bringing up these sorts of questions.

**Comment by Ainali** [comment]
These are very good questions. An idea that comes to my mind, is a label or similar on each requirement that establishes from what phase it is expected to be met.

**Comment by Ainali** [comment]
However, the current text form makes this perhaps a bit clunky to add. If we had the requirements in some structured format where we could have fields for this, it would be easier. This could also help towards #327, although they are not necessarily connected.

**Comment by ericherman** [comment]
Given the changes to _Document codebase maturity_ from #729, is there still something we want to do with this issue?

**Comment by Ainali** [comment]
No, I don't think so. Let's close this for now. If we get new specific ideas on how to utilize these ideas, we can always refer to this (and re-open if needed).
