### ISSUE TITLE
How does multiple repositories impact the publiccode.yml requirement?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#495]
[Create reusable and portable code](https://standard.publiccode.net/criteria/reusable-and-portable-codebases.html) has a requirement:

> Codebases SHOULD include a publiccode.yml metadata description so that they’re easily discoverable.

If a codebase has several repositories, do we want each repository to have a publiccode.yml file? Or is it enough if one has it? My intuition tells me one should be enough.  But Ialso feel that we should add something reuiring the relation to the other repositories need to be explained in that repository (perhaps in the README file).

**Comment by bvhme** [comment]
I think this depends on how the repositories are used. If they are independently usable solutions you could have many, or there could be just one for all of them. I don't think there is a clear answer that we could give, but perhaps the `publiccode.yml` standard could give us more insight on this.

**Comment by Ainali** [comment]
Good point! The reason I came to think of this was that one is being added to the Signalen frontend repository. And you could probably have another backend (or the other way around), but the itention is to use them together and I guess that it is this itention I think it would be nice to capture.

**Comment by Ainali** [comment]
It strikes me now, that repositories that are not independent of others should document their dependencies. And when I am looking, I can't find that we have any explicit written that dependencies should be documented. We do have:

> A codebase that is ready to use MUST only depend on other codebases that are also ready to use.

In [Document codebase maturity](https://standard.publiccode.net/criteria/document-maturity.html) which at least implies that they have to be known. And then we have:

> All policy and source code that the codebase is based on MUST be documented, reusable and portable.

In [Bundle policy and source code](https://standard.publiccode.net/criteria/bundle-policy-and-code.html) which I guess technically covers it, but is easy to forget the implications of when auditing".

Is this cause for a new requirement or guidance in "Developers and designers: what you need to do"?

**Comment by Ainali** [comment]
> Is this cause for a new requirement or guidance in "Developers and designers: what you need to do"?

We added guidance about dependencies in 1ee16e0cc5897df79767fdec65d889c4dfd9c030. Perhaps we can close this issue for now with that?

**Comment by ericherman** [comment]
As discussed, I'm closing this now. If someone wishes to put forward additional guidance in the Standard for Public Code, then we will re-open this.

Real-life examples should be highlighted in this discussion, and hopefully added to the implementation guide.
