### ISSUE TITLE
Clarify when "Code" means "Source Code" or "Policy Text"

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#496]
Feedback from policy makers is that the Standard should be clearer that source code and policy texts are two different things and use different words for them.

**Comment by ericherman** [comment]
Perhaps we should split 'All policy and source code that the codebase is based on MUST be documented, reusable and portable' into two requirements and be clear about what is expected of the policy and what is expected about the code.

**Comment by ElenaFdR** [comment]
The specific feedback received was:
> Code > by code you mean both source code and policy. You make that clear in your glossary. My advice however would be to just accept that (source) code and policy texts are two different things and keep using two words for them. The object of your standard is/should not be to say that they are one and the same; but instead that you can and should apply the best practices from writing code to writing policy texts (and maybe vice versa). See it from my side: if you would use the word ‘policy’ or even ‘text’ instead of code, you wouldn’t intuitively understand that that also means source code, and even after reading the glossary, you would have a hard time making the translation each time you see that word. NB. if you do want to keep using the word code, I suggest that you hyperlink to the glossary everywhere you use the word code.

**Comment by ElenaFdR** [comment]
#504 also led to a discussion of how we refer to policy and code.

**Comment by ericherman** [comment]
See also: #208
