### ISSUE TITLE
publiccode.yml: SHOULD or MAY?

### ISSUE THREAD

**Issue by raboof** [publiccodenet/standard#509]
https://github.com/publiccodenet/standard/blob/c7a30cb13d45dfd455af734442ad2e16073ea536/criteria/reusable-and-portable-codebases.md#requirements currently dictates codebases SHOULD include a publiccode.yml metadata description.

Do we really/still think this is a SHOULD? It seems more of a 'how' than a 'what', so while it seems like a neat thing to point people towards, perhaps it should be more of a suggestion than a requirement?

Related: #187, #495

**Comment by Ainali** [comment]
That is a great question. 

But seeing how important findability is to public code, this being specifically aimed at such, and that this is a specification already being used in some countries, I would almost lean in the other direction: making it a MUST. Writing one should only takes a few moments (if the codebase is mature enough to already be shareable in other aspects) so it shouldn't be a real blocker for any codebase.

**Comment by raboof** [comment]
I definitely agree it is an important topic and it is useful to make people aware of this metadata standard.

I would (unsurprisingly ;) ) not be a fan of making this a MUST: as it stands now, the Standard for Public Code encodes requirements that I think a "well-behaved" public/open project should have embraced anyway, regardless of whether or not they had seen the standard before. That makes it easy to recommend it to teams who may not have much experience working in the open. Requiring this particular technology, which is still emerging (less than 300 projects on GitHub have this metadata, even though apparently it's mandatory for all public software developed in Italy) seems overly prescriptive to me, and as such would make me less likely to recommend the Standard for Public Code.

> Writing one should only takes a few moments (if the codebase is mature enough to already be shareable in other aspects) so it shouldn't be a real blocker for any codebase.

I'm not sure it is a "zero-cost no-brainer", though: it raises questions like: "When my project consists of many repositories, are they all required to have a publiccode.yml? If so, how do I keep them in sync? If my language ecosystem also has different places to keep some of the same information, do I duplicate the information?", etc.

To be clear, I'm not trying to diminish the publiccode.yml initiative - I think it's great, deserves mention and hope it succeeds. Making it a requirement in the Standard for Public Code seems overly restrictive to me, though.

As mentioned in https://github.com/publiccodenet/standard/issues/327#issuecomment-873932817, apparently some users already feel a need to 'pick and choose' from the standard rather than adopting it entirely. I would really like it when most users can adopt the standard 'wholesale', which means being somewhat conservative in making sure the requirements are non-controversial. Of course this shouldn't be taken to the extreme - we shouldn't be so conservative that we no longer cause positive change - but I don't think we're at risk of that yet ;).

**Comment by Ainali** [comment]
Well, that is a fair point. May I then suggest another approach? What if, instead of changing the SHOULD to MAY for this particular technology, we rewrite it in a general way and just mentioning publiccode.yml as an example (like we do with documenting things in the README, CONTRIBUTING and GOVERNANCE)? Possibly something like: 

`Codebases MUST include a machine readable metadata description so that they’re easily discoverable, for example in a publiccode.yml file.`

I would argue that this is something that we would expect from a well-behaved public code codebase.

**Comment by ericherman** [comment]
I like the idea of adjusting the wording to specify intent, and then nudge the reader towards an implementation as an example -- I think we could do that straight away.

Changing form SHOULD to MUST is something I'd like us to discuss in a community call.

**Comment by ericherman** [comment]
@raboof please review https://github.com/publiccodenet/standard/pull/514

**Comment by ericherman** [comment]
82beaa2a09d7d5fd6fef1f8ca7a2fcdf54f89aba
