### ISSUE TITLE
Criteria navigation

### ISSUE THREAD

**Issue by jgroenen** [publiccodenet/standard#512]
I would really love to be able to navigate the criteria for ease of reading.
![screenshot-standard publiccode net-2021 07 26-10_47_56](https://user-images.githubusercontent.com/1716809/126961262-5550bc8f-8af6-4ad0-bc74-08b27853ad61.png)

**Comment by ericherman** [comment]
Is this issue different than https://github.com/publiccodenet/standard/issues/327 ?

**Comment by Ainali** [comment]
This is a really nice idea. If it's not too hard to implement, I would rather want to see something like:

[« Welcome contributors](https://standard.publiccode.net/criteria/open-to-contributions.html) · [Maintain version control »](https://standard.publiccode.net/criteria/version-control-and-history.html)

**Comment by ericherman** [comment]
Yes, I agree and I hope it wouldn't be too hard to do.

@Ainali I'll schedule some hack time for us to see if an hour-or-so of shaking our fists at the tools results in a PR that does this.

**Comment by ericherman** [comment]
This is now live: https://standard.publiccode.net/criteria/code-in-the-open.html and notice the "next" link to " Bundle policy and source code →"
