### ISSUE TITLE
Clarification about name branding?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#517]
The criterion [Use plain English](https://standard.publiccode.net/criteria/understandable-english-first.html) has a requirement about the name:

> The name of the codebase SHOULD be descriptive and free from acronyms, abbreviations, puns or branding.

However, the intention is not to make it a name with no branding intention, but to make sure there is no organizational or geographical branding of the participating organizations. Would it make it clearer if we spelled that out explicitly? For example:

> The name of the codebase SHOULD be descriptive and free from acronyms, abbreviations, puns or organizational branding.

**Comment by ericherman** [comment]
Yes, this is more clear.
