### ISSUE TITLE
Add Digital Public Goods badge

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#519]
We should add to the Standard that it is approved as Digital Public Goods. On the [printed version](https://github.com/publiccodenet/standard/blob/665e929f0c4bebea049915b2b096b44d52cc84a9/print.html) it would be fitting on the second page under the URL (line 284).

Where would it make sense in the online version?

Edit: 
- [x] Add badge on print.html
- [ ] Add badge in footer

**Comment by ericherman** [comment]
Maybe in the footer with version, copyright, license, etc.

**Comment by Ainali** [comment]
I believe the footer is entirely [footer-liquid](https://github.com/publiccodenet/jekyll-theme/blob/master/_includes/footer.liquid) in our Jekyll theme. How do we add something that should only show up in the footer on the Standard and not our other sites?
