### ISSUE TITLE
Advertise maturity: murky sentence

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#53]
Does:

## How to test
* No codebase marked with a less mature status is dependent on for this codebase

mean:
Any codebase should only depend on other codebases with the same or greater maturity level 
All released codebases must only rely on other released codebases (no less mature statuses)?

**Comment by bvhme** [comment]
Yes, to make sure you don't whilst unaware depend on some code that isn't
production ready yet.
