### ISSUE TITLE
File left over? Delete or link?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#531]
[_template.md](https://github.com/publiccodenet/standard/blob/develop/criteria/_template.md) seems to be a left over from when we started the standard. I think we either should delete or link it from the CONTRIBUTING (right now there are no links to this file).
Any thoughts?

**Comment by ericherman** [comment]
I do not think we should link it.
It seems to harm anything as it is not in the final output ( https://standard.publiccode.net/criteria/_template is a 404 )
That said, there may not be a lot of utility in keeping it, as we are unlikely to add many new pages; I think we can remove it.
