### ISSUE TITLE
Update docs/release.md to reflect github changes

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#553]
The pdf generation still references "front" and "back" cover, which is no longer needed.

The github UI has changed slightly, so the instructions regarding creating a release should not say "edit" but rather "release".

Also, we had to do "Trigger rebuild #552" in order to get the footer to update with the latest pdf which we had just generated.
Surely there is an order to avoid that.

**Comment by Ainali** [comment]
Removing front and back was fixed in #562, however step 8 still mentions sending the cover file, which I don't remember was needed when we printed 0.3.0.

Changing to releases was fixed in #592 

The third section was fixed in #623
