### ISSUE TITLE
Latest Standard PDF font is different

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#555]
This is uninteded, and not that important, however the font in the [latest release 0.2.2 PDF](https://github.com/publiccodenet/standard/releases/tag/0.2.2) differs from earlier releases. This is most likely because the generating person didn't have the font installed on their system.

Proposed solution:

1. Add installing the font to the generation and release instructions

Also, after the death of the designer the font Muli was forked and continued as Mulish, it might make sense to add that as a sensible first default to all the styles.g

**Comment by Ainali** [comment]
Fixed by #558
