### ISSUE TITLE
Idea: 'why is this important' before requirements

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#560]
The standard might become more readably for a wider audience if the criteria don't start with the, often tough and technical, requirements. Arguably, the 'why this is important' is the most important.

I'd propose putting the 'why this is important' before the requirements. This will make it a bit tougher to use the standard as a tool but I expect will vastly improve the speed someone can get acquainted with it.

**Comment by Ainali** [comment]
I like your reasoning for this. It's a quite large change though since most of the bullet points are written in the context of someone who have just read the requirements. We'll have to some more editing to them for them to make sense if we put them on top.

**Comment by ericherman** [comment]
@Ainali Yes, in order for this to be coherent, this is more than a cut-and-paste, however it should be something that the two of us can knock-out in a few working sessions. I suggest we create a branch for this and work on it incrementally. Shooting from the him, I expect we can find time to work through them all before end-of-january.

**Comment by ericherman** [comment]
It's worth reviewing #229 and #230 as we prioritize "Why" in the criteria layout.

**Comment by Ainali** [comment]
When doing this, some inspiration might be the videos we created for [the Standard course](https://citybycity.academy/course/standards-for-smart-cities) as they were an introduction that came before the requirements.

**Comment by ericherman** [comment]
When creating the first draft ( #811 ), many of the ideas expressed in "What this does not do" would naturally fit in the preambles. Would it make sense to hoist those up as well?

#813
