### ISSUE TITLE
[Bundle policy and source code] Account to business processes

### ISSUE THREAD

**Issue by MauriceHendriks** [publiccodenet/standard#568]
As an enhancement to `bundle policy and source code` it would be good if source code is accounted to the business processes affected. So how does the software enhance or service certain business processes. Ideally, the documentation should link to process descriptions.

@Ainali @ericherman

**Comment by Ainali** [comment]
Yes, agreed. In fact, I would already say that it is part of the requirements that exist. Reading the [glossary definition of policy](https://standard.publiccode.net/glossary.html#policy) I'd like to make the case for business processes being some sort of protocol and therefore included in what must be bundled. 

Do you think that we need to clarify the glossary term, or is it the "what you need to do" section that should be made clearer?

**Comment by ericherman** [comment]
I don't believe that clarify the glossary term would make the text clear enough on this topic.
I do not yet have a suggestion, yet I suspect we need to revisit the "why this is important" section as well.

**Comment by kerkuil** [comment]
As i said in our meeting, using the word `policy` as a container confuses more than it clarifies. How source code services business processes is one of those situations where the container concept of `policy` doesn't suffice.

A first suggestion to enhancing `Why this is important`:

>In order to know if (parts of a) solution is reuseable in another context, it must be clear in what context it was initially implemented. This implies that it's clear:
> - How (parts of) the solution is intended to reach a certain (logical) outcome and what was done to make sure that it does what it does (on a logical level).
> - To what legal requirements does the software relate to.
> - How the outcome was operationalized in business processes.
> - How the solution had improved those processes.
> - What a new adoptor of (parts of) the solution at least need to do integrate it in it's own context.
> - Where all the documentation can be found related to the above bullets.

**Comment by Ainali** [comment]
Just a note that we discussed this in the community call today: https://blog.publiccode.net/community%20call/2022/02/03/notes-from-community-call-3-february-2022.html

**Comment by kerkuil** [comment]
Let me ask some collegeaus to also review the changes done in relation to this issue.

**Comment by Ainali** [comment]
Note that #811included a rewrite of the discussed "Why this is important" section, as it was moved to be the introduction of the criterion. Is there still a need for clarification?
