### ISSUE TITLE
Style: do we use 'your codebase' or 'the codebase'?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#57]
'Your' presumes that everyone reading this is in some way responsible for or interested in a specific codebase (and that all of these criteria can be applied very concretely to a specific codebase).

**Comment by bvhme** [comment]
I would say let's not use your, except in the what to do points where we
should use your as much as possible

**Comment by ElenaFdR** [comment]
There are currently a number of places where that division doesn't quite work - for the criteria 'document your objectives', for example.
Suggest we discuss this in person!

**Comment by bvhme** [comment]
So, is this something we do away with (and close this issue) or would we like to solve this before 0.2.0?
