### ISSUE TITLE
Clarify dependency license requirements

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#574]
There is not clear text regarding dependency license requirements.

From [Publish with an open license](https://github.com/publiccodenet/standard/blob/develop/criteria/open-licenses.md):

> * All code and documentation MUST be licensed such that it may be freely reusable, changeable and redistributable.

From [Create reusable and portable code](https://github.com/publiccodenet/standard/blob/develop/criteria/reusable-and-portable-codebases.md)

> * The codebase MUST be independent from any secret, undisclosed, proprietary or non-open licensed code or services for execution and understanding.

What does this mean for optional dependencies?
What does this mean for supporting non-FOSS implementations?

If an organization's policy constrains my deployment choices for a dependency, say a database, would it still be in-keeping with the Standard for Public Code for us to, for example, create an app which works with any of PostgreSQL, MariaDB, Microsoft SQLServer, using a FOSS database for testing in the GitHub/GitLab continuous integrations, while deploying to the proprietary database in production because that's what the database administrators over in the ICT department can make available?

I believe the answer should be *yes*, yet that is not clear to me from the text of the criteria or requirements.

**Comment by raboof** [comment]
> I believe the answer should be _yes_, yet that is not clear to me from the text of the criteria or requirements.

I agree on both counts.

TBH while I it is of course a _virtue_ to only rely on open things, dependencies on proprietary things can be fine in some cases: for example it's of course _better_ to be cloud-independent, but having for example an AWS-specific component that adheres to the standard for public code would still make sense to me - even though AWS is decidedly proprietary...

**Comment by ericherman** [comment]
a02bfc0bee9b79484164edb6ffef9e7fa3c6543d was meant to close #570, not #574

**Comment by Ainali** [comment]
Hmm, reading this again, it feels like https://github.com/publiccodenet/standard/commit/a02bfc0bee9b79484164edb6ffef9e7fa3c6543d _do_ address this issue *as well as* #570.
