### ISSUE TITLE
Standard 14 on codebase maturity: what should this say?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#58]
@elenafdr changed this to:
Pay attention to codebase maturity

 @bvhme commented:
Perhaps this should be more active like "Advertise maturity"
(in https://github.com/publiccodenet/standard/pull/40_)

My logic for expanding it beyond just 'advertise' is that it currently includes instructions for not building code relying on less mature code. If there's more good practice or project management considerations that should be included, then making it clear from the title that it's broader than just putting a label on the code makes sense.

**Comment by clausmullie** [comment]
Oops, created duplicate with #137

the requirements only specify documentation, not really other proactive advertising or avoid risk of not building on less mature.

Shall we add something like this to the requirements then?
