### ISSUE TITLE
Dash clause separator: "n-dash" vs. "m-dash" vs. "hyphen-minus"

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#586]
In some places in the plain-ASCII dash (0x2D, in Unicode "hyphen-minus" U+002D) character is used as a clause separator.

However, in many places throughout the text, the Unicode EN DASH (U+2013) surrounded by spaces is used as a clause separator. 

American English style guides (e.g. Chicago Manual of Style, APA) recommend un-spaced EM DASHes (U+2014).

While I happen to think that un-spaced m-dashes look terrible compared to the (common in British English) variant of n-dashes with spaces, the rest of the text is in American English, thus we should either:

 * follow CMoS/APA
 * note this deviation from American English style in the CONTRIBUTING.md file
 * use ASCII-dash
 * make sentences more simple (rewrite uses of dash punctuation as clause separators)
 * something else?

Whatever we decide, adding a one-line in CONTRIBUTING seems like a good idea.

In the spirit of "Make contributing easy", there is something to be said for the less visually appealing "hyphen-minus".
In the spirit of "Use plain English", there is something to be said for more simple sentence construction. 

* https://en.wikipedia.org/wiki/Dash#En_dash_versus_em_dash

**Comment by Ainali** [comment]
In CONTRIBUTING I think we can add something like "Try to avoid dashes of different kinds by making your sentence more simple, but if that is the most clear way to convey something, use the ASCII-dash (the dash that commonly is the easiest one to type on a keyboard, also known as hyphen-minus)."

**Comment by ericherman** [comment]
I could certainly live with that.

**Comment by bvhme** [comment]
I don't have a strong opinion on this, and even feel that it could be fine for this to be inconsistent throughout the Standard. 

As standardizing, it might impose a greater cost than letting it be inconsistent. I've personally tried to follow [the Guardian's guidance](https://www.theguardian.com/guardian-observer-style-guide-d) on dashes, but that is arbitrary, and I don't propose that as guidance.

I feel the proposed addition to the contributing guidelines might impose a burden on the contributor that might not be valuable. In addition I fear it might make the writing process seem more technical than it should be.

If we do want consistency: I'd propose not dashing at all and guiding people to 'use simple sentences' and use commas or brackets if necessary.

**Comment by ericherman** [comment]
I agree with the concern that if we add something to CONTRIBUTING, it could work against the spirit of "make contributing easy", and as such any guidance there should be gentle and clearly non-blocking.

**Comment by Ainali** [comment]
To make it as easy to contribute as possible, and have the Standard not look sloppy, perhaps a solution is to not add anything complicated to the CONTRIBUTING and instead add some guidelines in the release process of aligning the use of dashes to how we want it? That way, we can merge contributions as is, and contributors don't really need to know anything about typography and the Standard can also look very professional.

**Comment by ericherman** [comment]
Documenting our style choices as part of the pre-release process neatly sidesteps the tension; I like it.

There I think we can, and should, provide guidance to look for opportunities to (in the spirit of "Use plain English") favor more simple sentence construction over using dashes.

We can also decide which dash style to favor in the remaining locations, with a note that we do not have to be overly strict or dogmatic about it.
