### ISSUE TITLE
Move DPG logo in print version to be small and on the cover like the HTML version

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#593]
Today, even though `width` and `height` are set in `print.html` the DPG logo in the print version is large and rendered on its own page when rendered by `weasyprint`.

It would be better to have the logo small and on the front cover, as in the HTML rendering.

**Comment by Ainali** [comment]
Hmm, the strange thing is that it looks like dpg-badge.svg already is set to be 92 by 46 pixels.
