### ISSUE TITLE
pdf download link broken

### ISSUE THREAD

**Issue by jgroenen** [publiccodenet/standard#597]
I'd like to report an issue in `index.md`

The pdf download link is broken, because of version update. Maybe (also) link to https://github.com/publiccodenet/standard/releases/ for the latest version pdf download

**Comment by Ainali** [comment]
Yes, I can replicate it, and it is surely related to our hotfix. 
We'll look into it more closely tomorrow. Thanks for reporting!

**Comment by ericherman** [comment]
I tagged the original (pre-hotfix) version as 0.2.3-0 and then `git tag --force 0.2.3` to be the same was 0.2.3-1, then `git push --force --tags`. In the GitHub release page, I changed the release to point to 0.2.3, which is now the same content as 0.2.3-1. Should anybody desire, the pre-hotfix version can be easily found and viewed using the 0.2.3-0 tag.

**Comment by ericherman** [comment]
Thanks @jgroenen! This could have gone by a long time before any foundation staff noticed it.

**Comment by jgroenen** [comment]
Was someone in the code for NL community who noticed it actually! I thought I'd just make an issue. Thanks for the quick response!
