### ISSUE TITLE
Define the audience

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#6]
So that we can use 2nd person singular verb tenses. 
Proposal: the audience is a person who will need to follow/implement that standard. (So a 'you must' instruction always presumes it's within the gift of the reader to do this, without needing to define who the reader is.)

**Comment by bvhme** [comment]
In the [introduction we've defined a target audience](https://github.com/publiccodenet/standard/blob/develop/introduction.md#who-is-this-guidanance-for), however these are multiple, so perhaps we need to find a way to make clear someone in their development process, policy management or developer needs to do this to comply.

**Comment by ElenaFdR** [comment]
Closing because:
- the intro clearly defines the audience
- my concern about second person pronouns is covered in #57.
