### ISSUE TITLE
Clear up overlap between "Code in the open" and "Bundle policy and source code"

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#600]
The requirement "All source code for any policy and software in use (unless used for fraud detection) MUST be published and publicly accessible." has an unfortunate overlap with "Bundle policy and source code"

We have seen in others' self assessments that it is not clear if the requirement is met" in the case of all source code is published in the open, but the policy is unknown or not referenced.

A potent clarification might be to split the requirement in "Code in the open" into two separate requirements, one for source code and one for policy.

**Comment by Ainali** [comment]
So perhaps changing it to these two?

1. All source code for any policy in use MUST be published and publicly accessible.
2. All source code for any software in use (unless used for fraud detection) MUST be published and publicly accessible.

**Comment by Ainali** [comment]
Se also the discussion in #332.
