### ISSUE TITLE
Make release 0.3.0

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#609]
We aim to [do a release](https://github.com/publiccodenet/standard/blob/develop/docs/releasing.md) quite soon (hopefully in the coming week) to implement the revert of the Mermaid diagram (in #607) and to get the guidlines about small contributions in. That is a change that will bump us to 0.2.4.

**Comment by Ainali** [comment]
Oh, since we are changing a should to a must and adding a requirement, this should be 0.3.0!

**Comment by ericherman** [comment]
https://github.com/publiccodenet/standard/releases/tag/0.3.0
