### ISSUE TITLE
No way to find community translations from the main standard

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#610]
Though settting up [https://github.com/publiccodenet/community-translations-standard](https://github.com/publiccodenet/community-translations-standard) solved #336, there's no way to discover it exists from the ENG standard (the URL we share most widely).
If people don't know it exists, it won't help people in a non-ENG professional context who judge that the standard being in English is an insurmountable obstacle.

Suggested solution:

- Add this sentence as a new, standalone final paragraph before the contents on the [index](https://standard.publiccode.net/):  There are also informal [community translations of the Standard] in other languages.
- make 'community translations' a hyperlink to the [community translations repo](https://github.com/publiccodenet/community-translations-standard) on the [Version 0.2.3 changelog](https://standard.publiccode.net/CHANGELOG.html#version-023)

**Comment by Ainali** [comment]
This is a sharp observation and something we should address.
Is it perhaps even worth to add a link in the site footer after the DPG badge? Simply: [Community translations of the Standard]

**Comment by ElenaFdR** [comment]
Possibly? I'd caution against making that the only link, since many people don't read to the bottom of a page online, and this is important enough info to put it above the fold.

**Comment by Ainali** [comment]
I meant that as in addition to your suggestions.

**Comment by Ainali** [comment]
It could possibly also get added at the end of the Introduction under the heading **Get involved**.
