### ISSUE TITLE
Bundle policy and code: invite policy makers to contribute their own work in their own formats

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#62]
'Bundle policy and code' encourages policy experts to use flowcharts (effectively) to chart the policy, but doesn't say anything about the formats for presenting policy that are more commonly used by policy people - probably something more like a long article or essay, potentially with graphs or diagrams.
Suggestions:
- Invite them to include their original policy papers (the work they did for their peers) so long as there's an English language translation
- Invite them to link to any explanations of the policy produced by the public administration for comms purposes (for example, for residents, or to sell the new policy politically)
- Make sure there's a cross reference from here to policy documentation in 'document your objectives'

**Comment by ElenaFdR** [comment]
Additional thought: where either the code or the policy have to reference something that's specific to that policy environment (especially if in a non-English language), please include a brief English intro (eg Wikipedia link) to the concept.

**Comment by ericherman** [comment]
@ElenaFdR when you say "invite" do you envision a MAY criteria or guidance text in the "Policy makers: what you need to do" section?

**Comment by Ainali** [comment]
Let's plan a working session on this topic. We've recently gotten some feedback that also addresses this that we can incorporate.

**Comment by Ainali** [comment]
Addressed by #504 and #505. If something is still missing, please create a new issue more narrow issue.
