### ISSUE TITLE
Unclear nuance with MUST and SHOULD requirements around (potential) security issues 

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#632]
The criterion [Make contributing easy](https://github.com/publiccodenet/standard/blob/develop/criteria/make-contributing-easy.md) has two related requirements, however the nuance between them lacks clarity:

* The codebase MUST include instructions for how to privately report security issues for responsible disclosure.
* The documentation SHOULD include instructions for how to report potentially security sensitive issues on a closed channel.

**Comment by Ainali** [comment]
The nuance was more distinct before #415. Perhaps "instructions" in the MUST criteria should be changed for "a way", "a method" or something similar so that we're not talking about "instructions" twice?

**Comment by ericherman** [comment]
Would it be better to change the MUST from "instructions" to "a method" or ... can we drop the SHOULD requirement?

**Comment by Ainali** [comment]
I think we should change the MUST, because right now having a method at all is only implicit and that is not a great way to write important requirements.

**Comment by ericherman** [comment]
Zooming out, would it be better to transform the SHOULD requirement to be about publishing the processes and polices for responding?

For example: https://github.com/open-zaak/open-zaak/blob/main/SECURITY.rst

**Comment by Ainali** [comment]
I think that if we change the MUST to be explicit about a method, the SHOULD can remain the same. Then we might want to add a MAY requirement about also publishing the processes and polices for responding.

**Comment by ericherman** [comment]
Looking at d0dbb84d94b3bd26427f5d2f37a0ced9687c039c the change from "email address" to instructions essentially combined the two requirements; I lean towards deleting the SHOULD.
