### ISSUE TITLE
No explicit mention of maintainer or product-owner contact details

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#633]
The criterion [Make contributing easy](https://github.com/publiccodenet/standard/blob/develop/criteria/make-contributing-easy.md) contains the requirements:

* The codebase MUST have a public issue tracker that accepts suggestions from anyone.
* The codebase MUST have communication channels for users and developers, for example email lists.

However, multiple people have expressed a desire to have "findability of the people behind the codebase" -- a way to contact the people responsible for the product steering or technical steering of the codebase.

**Comment by ericherman** [comment]
Recently, this was raised in the [June 2022 Standard for Public Code community call](https://blog.publiccode.net/community%20call/2022/06/08/notes-from-community-call-2-june-2022.html), and has been raised separately in emails.

**Comment by Ainali** [comment]
However, in [Welcome contributors](https://standard.publiccode.net/criteria/open-to-contributions.html) we have:

* The codebase SHOULD advertise the committed engagement of involved organizations in the development and maintenance.

Granted, this is still not a way to contact people, but at least give a clue of where the people come from. 

In the same criterion we also have

* The codebase MUST document the governance of the codebase, contributions and its community, for example in a GOVERNANCE file.

It's unlikely that any governance that has a technical or product steering wouldn't mention the people of those groups there. Still, that might only be names and not contact methods.

Hovwever, given that we have requirements about communication channels, visibility of organizations and likely naming people, I wonder if that is not enough. Have we heard from someone who has looked at a codebase that offers all this and they had said "it's not enough" or have we mostly heard from people that are looking at codebases that are not even compliant with these requirements?

**Comment by ericherman** [comment]
Perhaps adding a line to "What you need to do" or "How to test" could clarify this.

**Comment by Ainali** [comment]
Yes, that might be a good idea. One bullet point could be for managers in Make contributing easy:

* Make sure that everyone involved have access to and can use the selected communication channels.

**Comment by Aidenbuis** [comment]
It might be interesting to add the contact information for general inquiries about the project in the README.md file. I can imagine that some people will 'bounce' after not finding the information at first glance.

**Comment by Ainali** [comment]
> It might be interesting to add the contact information for general inquiries about the project in the README.md file. I can imagine that some people will 'bounce' after not finding the information at first glance.

Are you imagining "contact information for general inquiries" to be something like `info@example.com` or would an email list or chat link suffice?

**Comment by Aidenbuis** [comment]
I think that a traditional email link would make conversion the highest for some people viewing the codebase, like non-technical managers.

**Comment by ericherman** [comment]
Something like an "info@codebase.example.org" would allow for anybody -- regardless of technical level -- to have a low barrier way to ask a question, but is that an additional SHOULD requirement? Or a  MAY? Or just a "nice to have" on codebases which have all of the other information well documented?

Even if only a "nice to have", I think this we can add something to Guidance.

**Comment by Aidenbuis** [comment]
I don't think it should be a SHOULD, but would suggest it to be a MAY as it increases the potential for reuse and collaboration.

**Comment by Ainali** [comment]
I just remembered that we also have the requirement: 

> The codebase SHOULD include a machine-readable metadata description, for example in a [publiccode.yml](https://github.com/publiccodeyml/publiccode.yml) file.

Most metadata descriptions include contact details, and indeed in publiccode.yml a contact is mandatory.

I think this means that we do not need to add any new requirements. However, guidance about contact details might be good, as adding it to the README still might be worth recommending since the publiccode.yml file might not be obvious to everybody to look in.
