### ISSUE TITLE
Requirements with sub-bullets make evaluation more complex than multiple individual requirements

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#634]
For example https://standard.publiccode.net/criteria/documenting.html

Let's review each and see if it would be as good or better to break up these compound requirements.

**Comment by Ainali** [comment]
I agree, and I think all of those could fairly straightforward be transformed into separate requirements. 

There's only one other sub-bullet point list in the requirements, and that's in [Document codebase maturity](https://standard.publiccode.net/criteria/document-maturity.html). The difference is that those are not separate requirements, so the solution would be different. Perhaps we could there instead to refer to some external definition? Something like:

> A codebase that is not yet ready to use MUST have one of the labels `prototype`, `alpha`, `beta`, or `pre-release version` as specified by RFC XXXX.

**Comment by ericherman** [comment]
I don't believe there is an RFC or know of a similar standard that we can easily link. However, I think we can make it a list and then move the definitions down to the "what you must do" guidance.
