### ISSUE TITLE
Redundant requirements between "Bundle policy and source code" and "Create reusable and portable code" and "Document the code"

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#645]
"All policy and source code that the codebase is based on MUST be documented, reusable and portable."

**Comment by ericherman** [comment]
As in #600 , split between policy and code may illuminate how these are different.

**Comment by ericherman** [comment]
Se also the discussion in #332

**Comment by Ainali** [comment]
In our work session today, reviewing #332, #600 and #676, @ericherman concluded that this requirement does not really add anything that is not covered by other requirements in the standard. Therefore, we suggest that we remove it completely.
