### ISSUE TITLE
Move requirement from Code in the open to Bundle policy and source code

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#646]
The MAY requirement in [Code in the open](https://standard.publiccode.net/criteria/code-in-the-open.html) 

> The source code MAY provide the general public with insight into which source code or policy underpins any specific interaction they have with an organization.

feels like it would fit better in [Bundle policy and source code](https://standard.publiccode.net/criteria/bundle-policy-and-code.html).

**Comment by ericherman** [comment]
Granted, there is "openness" in providing insight yet this explanation about why software was funded/created is more closely related to the policy than working in the open.

**Comment by Ainali** [comment]
I guess that if the focus is on "the general public" it could perhaps stay, but we should perhaps add some guidance in "Why this is important" to explain why it is there.

**Comment by ericherman** [comment]
Adding "why this is important" would be useful, agreed

**Comment by ericherman** [comment]
Which criteria it falls under is still a question, let's write the "why" and let that inform our thinking on the location.
