### ISSUE TITLE
Improve tone and sharpen purpose of text on back of printed cover.

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#654]
Text should concisely and clearly express what the standard provides, rather than state beliefs.

**Comment by brandmuse** [comment]
These are good places to start. I'd write

The standard for Public code includes guidance to policymakers, managers, designers and developers creating and managing codebases. The criteria of the standard support the collaborative creation of codebases that are usable, open, legible, accountable, accessible and sustainable.

**Comment by ericherman** [comment]
Similar text appears in the [README.md](https://github.com/publiccodenet/standard/#readme) as well

**Comment by ericherman** [comment]
What about reversing the sentence order of the suggestion from @brandmuse ?

> The Standard for Public Code supports the collaborative creation of codebases that are usable, open, legible, accountable, accessible and sustainable. The Standard includes guidance to policymakers, managers, designers and developers creating and managing codebases.

**Comment by brandmuse** [comment]
> 

This works totally!
