### ISSUE TITLE
Replace MAY with OPTIONAL in requirements

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#668]
The word "may" is not as clear English as "optional" as our usage for "may" is not permitting discouraged behaviour, but rather encouraging non-essential behaviour.

Where we have requirements which constrain discouraged behaviour, we write them as SHOULD NOT or MUST NOT.

https://datatracker.ietf.org/doc/html/rfc2119#section-5

**Comment by Ainali** [comment]
Thinking about this I am not sure exactly how to structure the sentences to not be too clunky. My suggestion for now is to lead with the word OPTIONALLY. Example:

> The source code MAY provide the general public with insight into which source code or policy underpins any specific interaction they have with an organization.

would turn into

> OPTIONALLY, the codebase can provide the general public with insight into which source code or policy underpins any specific interaction they have with an organization.

Any other suggestions or should I use that as a base?

**Comment by ericherman** [comment]
In this case, I believe the requirement is somewhat poorly written to begin with. The source code shouldn't do this, the codebase documentation should.

> Documentaion MAY provide the general public with insight into which source code or policy underpins any specific interaction they have with an organization.

I think leading with OPTIONALLY would be fine. Also combined with "may" in lower case.

> OPTIONALLY, the source code may provide the general public with insight into which source code or policy underpins any specific interaction they have with an organization.

Alternatively, lead with "It is OPTIONAL":

> It is OPTIONAL for the source code to provide the general public with insight into which source code or policy underpins any specific interaction they have with an organization.

Or perhaps, if we agree that it is an aspect of codebase documentation, it could be something like:

> Providing the general public with insight into which source code or policy underpins any specific interaction they have with an organization in the codebase documentation is OPTIONAL.

or:

> Documenting which source code or policy underpins any specific interaction the general public may have with an organization is OPTIONAL.

**Comment by Ainali** [comment]
I agree with you, I was confused and thought only OPTIONALLY was a keyword in RFC 2119 but that's not the case. Only OPTIONAL is listed there, so let's go with that.
