### ISSUE TITLE
What would it mean for a file in the codebase to not be in version control?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#670]
In [Maintain version control](https://standard.publiccode.net/criteria/version-control-and-history.html) we say: 

> All files in a codebase MUST be version controlled.

But if the codebase is using version control, how could we say that a file that is not in version control is part of the codebase?

**Comment by ericherman** [comment]
An argument could be made that files generated by the build process are also part of the codebase, yet clearly that is not what this requirement is about.

An argument could be made that configuration files used by the build or the deployment could also be considered part of the codebase ... again, this is not what this requirement is about.

Given the first requirement only specifies "code", and not other supporting files:

* The community MUST have a way to maintain version control for the code.

The addition of:

* All files in a codebase MUST be version controlled.

perhaps aims to clarify that all files types, not just source code files, should be version-controlled ... if so, I hope we can find more clear wording, perhaps by rewording the first bullet.

**Comment by Ainali** [comment]
Perhaps it is good as it is, but that we need to have this in mind when looking at other requirements.

For example, if someone, related to another requirement, says: "yes, we have that documentation over here" and that place is not version controlled we could say: "okay, but as it is not in version control, it is not *in* the codebase yet".
