### ISSUE TITLE
Requirement for code comments belongs in Document the code

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#671]
In [Use a coherent style](https://standard.publiccode.net/criteria/style.html) we say:

> The codebase SHOULD include inline comments and documentation for non-trivial sections.

I think that would fit much better in the criterion [Document the code](https://standard.publiccode.net/criteria/documenting.html).

**Comment by ericherman** [comment]
fixed by: 679b039cd7c0067b27035ae5a5b71acf7b20600c
