### ISSUE TITLE
Document codebase maturity uses the ambiguous term 'pre-release'

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#708]
As of 0.4.0 the criterion 'Document codebase maturity` contains the requirement:

* A codebase that is not yet ready to use MUST have one of the labels: prototype, alpha, beta or pre-release version.

Guidance is given to label "code that is ready to be released but hasn't received formal approval yet" as "pre-release version".

However, 'pre-release' has a different meaning for many developers. For instance [GitHub releasing docs](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) state
> To notify users that the release is not ready for production and may be unstable, select This is a pre-release.

**Comment by ericherman** [comment]
Commonly, code that is believed ready for release is labelled '[release candidate](https://en.wikipedia.org/wiki/Software_release_life_cycle)'

**Comment by Ainali** [comment]
See also the discussion in #706.

**Comment by ericherman** [comment]
I would like a good source for standard practice in public code (or even FOSS in general) for this requirement to cite. So far my web searches ( and looking at https://en.wikipedia.org/wiki/Software_release_life_cycle#References ) haven't unvovered a really strong source in my eyes.
