### ISSUE TITLE
The license file is repo is improperly formatted

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#709]
Look at the last paragraph of

* [https://github.com/publiccodenet/standard/blob/develop/LICENSE.md](https://github.com/publiccodenet/standard/blob/develop/LICENSE.md)

and compare to last paragraph of:

* [https://creativecommons.org/publicdomain/zero/1.0/legalcode](https://creativecommons.org/publicdomain/zero/1.0/legalcode)

It seems as though in an attempt to reformat the text to markdown, an error was made.

**Comment by ericherman** [comment]
I question the value of reformatting the code ourselves.

If we can find an authoritative version, let's use that.

When a GitHub repository is initialized with CC0, GitHub's tooling adds a plain-text `LICENSE` file. Perhaps plain text would be fine?

**Comment by Ainali** [comment]
The quick fix is to change the last bullet point d to 4 so that it renders.

I guess the markdown conversion was made as it makes it easier to read in the printed version.

**Comment by ericherman** [comment]
Summarizing a conversation:

Important to note is that the sub-sections under section 4 "Limitations and Disclaimers.' are letters, not roman numerals. Today the repository version shows subsection "ii" while the official version is subsection "b"; we need to address this aspect as well.

The repository version should be verifiable with a clean `diff` against any new repository created with a CC0-1.0-Universal license.

If we want to include a more nicely formatted version for print, @Ainali had the idea that maybe the official (and nicley formatted) [https://creativecommons.org/publicdomain/zero/1.0/legalcode](https://creativecommons.org/publicdomain/zero/1.0/legalcode) could possible used, hiding everything except the license text via CSS.
