### ISSUE TITLE
How to search for the Standard for Public Code in natural language?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#740]
In [Make the codebase findable](https://standard.publiccode.net/criteria/findability.html), we say:

> The codebase MUST be findable using a search engine by describing the problem it solves in natural language.

What would we like people to search for and find the Standard for Public Code? Here are some suggestions:

* Method for public organizations to collaboratively develop software
* Best practices in open source software development for public organizations
* Standard to enable collaboration in software development by the public sector

**Comment by ericherman** [comment]
searching for:
"government software standard" does not find the Standard on any of bing, google, or duckduckgo
"public sector software standard" only founds the Standard in google, not bing or duckduckgo

**Comment by ericherman** [comment]
The following were provided by a vendor in the space:

- open source (code) best/common practices
- how to manage an open source project
- open source (code/project) for dummies
- do's and don'ts open source (code/project)
- how to start/manage your own open source code/project for professional/company

**Comment by ericherman** [comment]
This morning, using a "private browser" firefox window for google.com to search for "guidelines for open source development by government" the Standard for Public Code shows up on the 80th link.

**Comment by ericherman** [comment]
The changes in https://github.com/publiccodenet/standard/pull/910 provide requirements for a short description specified in the codebase which can be used as natural language search.
