### ISSUE TITLE
Add e-reader formats to release process

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#743]
In #374, the idea was put forward that in addition to PDF, other formats could be generated as well.

**Comment by ElenaFdR** [comment]
MOBI's [on its way out](https://boingboing.net/2022/05/03/kindle-finally-supports-epub-but-will-kill-mobi.html).

**Comment by Ainali** [comment]
I was looking at Calibre which can generate epub, but realized that both the pdf and print.html is formatted to be two pages side by side. For optimal epub, we need a simpler CSS that just uses one sided layout.
