### ISSUE TITLE
Focus on contributions, review or existence of a style guide?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#754]
In [Use a coherent style](https://standard.publiccode.net/criteria/style.html) we say:

> * Contributions MUST adhere to either a coding or writing style guide, either the codebase community's own or an existing one that is advertised in or part of the codebase.

But I wonder if it wouldn't be better to state something about that the reviews must check contributions to see if they adhere to those instead. That will make it easier to see if there are guidelines or templates for the reviewers. We could change it to something like:

> * Reviewers MUST check that contributions adhere to either a coding or writing style guide, either the codebase community's own or an existing one that is advertised in or part of the codebase.

However, we could also focus on the guides rather than the contributions or reviews, which would be _much_ easier to assess. If we want to go that route, we could change it to something like:

> * The codebase MUST advertise a coding or writing style guide, either the codebase community's own or an existing one referred to in the codebase.

**Comment by ericherman** [comment]
I like the emphasis on the _codebase_ _documentation_ rather than the _reviewers'_  _behaviour_
