### ISSUE TITLE
The how to test is sometime impossible to

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#80]
How to test that something was tested with users adds considerable overhead, how can we support this criterium in a different way, or is this a service criterium and thus out of scope?

**Comment by ElenaFdR** [comment]
The current version is my rewording of something that wasn't very clear; I'm very happy to change it. It still wouldn't be an automatic test, but we could suggest feeding documentation into http://www.hemingwayapp.com/ with every major new release.

**Comment by bvhme** [comment]
There is some trouble here concerning what is a 'major' release as well. As when using _semantic versioning_ there is a strong point to be made that _major_ versions don't introduce any new functionality (in order to make migrating to the new interfaces easy) while you would like the tests to be performed when new functionality is introduced.

**Comment by MirjamvT** [comment]
on the page 'coding in the open':
The sentence below ‘## How to test’ does not tell the reader how to test!? 
It tells the reader how to ‘reach’ the text/code. 
let's be more precise. i now do not understand what is supposed to be tested and when and by whom, when i read this. also, not clear when the test is passed. or how that would be visible to others.

**Comment by MirjamvT** [comment]
also: If it (how to test) is a question, should there be a question mark? alternative suggestion for header: On how to test (this is not a question, and does not 'need' a question mark.

my preference is to make this header (and the same on on other pages) more precise, like: How to test x for y 
in order to make it more clear what the test will help accomplish

**Comment by bvhme** [comment]
@MirjamvT if you are testing for 'code is published and open' telling someone how to reach it _is_ testing whether it is compiant.

Second point I agree, for style I suggest adhering to something like __Given that ... when I .... then ... __

**Comment by clausmullie** [comment]
This discussion is linked to  #141

Will close that, comment copy-paste below
```
Is testing the right word to use in our standard?

I personally feel like 'test' could be used to everything that machines do (such as continuous integration and so forth) while 'evaluate' could be used for everything humans do.

Many of the requirements we have do not have a objectively defined testable outcome but a subjectively qualifier (ie 'good documentation' is not objective)
```

**Comment by ericherman** [comment]
We have various proposals to replace "test" including:
* evaluate
* verify
* check

But I think it is beyond replacing the word "test" ... I have the growing sense that even the "How" in "How to test" is not a good word for these sections. In some cases the section would make more sense as a list of "what to check", as they are less about "how" to test. In some cases (e.g.: "all files in a codebase must be version controlled" in [Maintain version control](https://github.com/publiccodenet/standard/blob/develop/criteria/version-control-and-history.md)) the how to test would be essentially restating the criterion itself. It is as if some of these "How to test" guidance lists are highlights of items to consider during the evaluation of the criteria but are not fully encompassing of the individual criteria of the section.

**Comment by ericherman** [comment]
I'd like snappy wording for "Considerations during evaluating and extra things to check" ....

**Comment by ericherman** [comment]
Would it work better to rephrase the "How to test" items as "Questions to ask"?

**Comment by ericherman** [comment]
Closing this issue in favor of https://github.com/publiccodenet/standard/issues/314 which aims to address this specifically.
