### ISSUE TITLE
Review "What does this not do" sections 

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#813]
Many bullet points in the What does this not do section feels like they are added more for checking a box so that we have something in that section, rather than that they add some value. We should review them all to make sure we don't have any that are "just for show".

**Comment by ericherman** [comment]
Looking at #560 it seems that the ones which are not "checking a box", could fit naturally in the preamble; perhaps we should "hoist" those up.

**Comment by Ainali** [comment]
This will be the topic for the community call on Thursday, 2 March.

**Comment by Ainali** [comment]
After a review of all criteria, we think that no one is really on topic and adding value to the reader.

In one case, Require review of contributions, we believe that the introduction could be expanded based on one of the bullet points, and for Use an open license it inspired some new text that could be added to the introduction. With that, I feel that the seemingly radical suggestion to remove all sections would make sense.

**Comment by ericherman** [comment]
I think we should remove the text under what this does not "Mean that reviewers are liable" because that may not be factual in all jurisdictions.
