### ISSUE TITLE
Add requirement for sitemap to Make the codebase findable

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#835]
Sitemaps are an open and established standard for describing a website and it is used by most search engines.
The standard is described at: https://www.sitemaps.org/protocol.html

It can also be verified by open tools like https://validator.w3.org/

I propose that we add a requirement to the standard that requires a codebase's website to use a sitemap.

**Comment by ericherman** [comment]
Would guidance to developers be the right place for this? I'm thinking that the codebase community of users and contributors may not use it directly, rather it's presence would support search engine's and making the codebase findable.
