### ISSUE TITLE
Should there be a requirement for license compatibility?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#849]
Not all open source licenses are compatible with each other, and since we do allow multiple licenses, perhaps we should have a requirement that if code have different licenses, the way the code is combined must be done so that all licenses are adhered to?

(If all files have machine-readable licenses, this could possibly be checked for with a script/tool.)

**Comment by ericherman** [comment]
Rather than an additional requirement, would it be enough to have a line or two in the guidance to developers or managers?

**Comment by Ainali** [comment]
Yes, I think that would be enough. And perhaps in the implementation guide we can link to some tool.

**Comment by Ainali** [comment]
Created publiccodenet/community-implementation-guide-standard#40
