### ISSUE TITLE
Focus on marketing instead of the problem

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#896]
In [Make the codebase findable](https://standard.publiccode.net/criteria/findability.html), we say:

> The codebase MUST be findable using a search engine by describing the problem it solves in natural language.

However, for many codebases, it is hard to know exactly what the problem it solves is or the type of codebase is already so well-known that any search for it will include a mention of the type. Perhaps this should instead focus on that the codebase should be findable through the way it markets itself, rather than guessing how others will try to find it.

**Comment by ericherman** [comment]
For codebases that are already quite popular, it is easy to find them using natural language. However, for less widely used codebases, my testing highlighted that even searching for the phrase used in the repository's description does not get a repository link in the first few pages of the biggest search engine.

Perhaps this requirement should need to change from `MUST` to `SHOULD` or `OPTIONAL` as it still relies too heavily search-engine-optimization which is depends on things outside of the codebase community's control.

**Comment by Ainali** [comment]
[Notes from the community call](https://blog.publiccode.net/community%20call/2023/04/11/notes-from-community-call-6-april-2023.html).

Important for this issue, the call agreed in lowering the degree from MUST to either SHOULD or OPTIONAL.
