### ISSUE TITLE
Add requirement for a short high-level description of the codebase

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#899]
In [the last community call](https://blog.publiccode.net/community%20call/2023/04/11/notes-from-community-call-6-april-2023.html) when talking about findability of a codebase, it was brought up that having a good short description of it is important. It should be short enough to be possible to use in the repository description field and in the bio of any social media handles for the codebase. I suggest going for a SHOULD requirement.

**Comment by ericherman** [comment]
Possibly this should be documentation guidance rather than a requirement.

That said, a brief review of relevant codebase repositories hosted here on GitHub as well as GitLab and others show that most already have this, thus this would not be an arduous addition.
