### ISSUE TITLE
Automate {{ site.version }} to have the tag, rather than a hand-updated field in _config.yml

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#929]
When creating release candidates or development versions, the site.version number is the same as the previous release (or potential the next release) which means that the `.pdf``s are slightly wrong and a source of some confusion.

**Comment by bvhme** [comment]
The reason this wasn't done in the past was because the tagging action to trigger the release would not trigger GH-pages to build the site, thus after releasing the version number was always outdated.

**Comment by ericherman** [comment]
Now that the tag triggers the build, this would not be the case.
