### ISSUE TITLE
Criteria Checklist

### ISSUE THREAD

**Issue by fliepeltje** [publiccodenet/standard#939]
It would be great if at the end there is just a (printable) page of checkboxes that you can go through to validate an entire codebase; the document can be a nice reference to items on the checklist, but just a single overview would greatly decrease the barrier for assessing an existing codebase and could facilitate making automated tools (like a github action or a cli checker) for repositories

**Comment by Ainali** [comment]
We have a [review template](https://github.com/publiccodenet/standard/blob/develop/docs/review-template.html), which is also rendered as a PDF and attached to every release. Here is [a link to the version 0.6.0 one](https://github.com/publiccodenet/standard/releases/download/0.6.0/standard-review-template-0.6.0.pdf). Is that what you are looking for?

**Comment by fliepeltje** [comment]
Ah yes, that's perfect! I overlooked that, but it is exactly what I was looking for. Thanks! :)
