### ISSUE TITLE
Clarify/specify review time

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#980]
In [Require review of contributions](https://standard.publiccode.net/criteria/require-review-of-contributions.html) we have the requirement: 

> Reviews SHOULD happen within two business days.

We should clarify that, so it does not seem like the intention is that one has to finish the review within two business days.

**Comment by Ainali** [comment]
[Notes from last community call](https://blog.publiccode.net/community%20call/2023/09/11/notes-from-community-call-7-september-2023.html) when this was discussed.

In summary, we should expand our How to test section so that it is clear what the expectations are.

**Comment by ericherman** [comment]
In how to test, we can suggest to check for the presence of a policy or statement of intent, and we can review contributions to see the pattern of how the policy is being followed in practice.
