### ISSUE TITLE
Use Semantic line breaks as style?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#986]
In our CONTRIBUTING, we already mention one sentence per line.
Should we formalize this as saying that we aim to adhere to the [Semantic Line Breaks specification](https://sembr.org/)?
This could make the text even easier to diff in the future.

(The specification was found through the [Open Source Project Template's preferred style](https://github.com/diggsweden/open-source-project-template/blob/main/CONTRIBUTING.adoc#writing-style-and-translations).)

**Comment by ericherman** [comment]
I would be happy-enough to try out this idea, perhaps in an experimental branch of the standard?

**Comment by ericherman** [comment]
With the ideas for sembr.org, one would like to change:

```
* All source code for any policy in use (unless used for fraud detection) MUST be published and publicly accessible.
* All source code for any software in use (unless used for fraud detection) MUST be published and publicly accessible.
```

to be something like:

```
* All source code for any policy in use
   (unless used for fraud detection)
   MUST be published and publicly accessible.
* All source code for any software in use
   (unless used for fraud detection)
   MUST be published and publicly accessible.
```

However, I do not believe it is possible to use line-breaks in Markdown list items.

The Standard relies heavily on Markdown bullet lists. As the ideas in sembr don't seem work there, I think it's a no-go for the Standard unless it were to move away from Markdown to a format which allows list items to span lines (e.g.: HTML or LaTeX) ... or if it were to move away from use of lists.

**Comment by Ainali** [comment]
Closed, as we couldn't see how this could add value due to our current formatting.
