### ISSUE TITLE
missing for community translations being included in the repository

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#994]
If a codebase has officially supported translations which are located in the repository, it should also be possible for the repository to contain unsupported/community-best-effort translations in the same repository structure.

Which languages would block a release and are officially supported should be prominently documented.
It should also be clear what languages are incomplete or best-effort community translations.

As written today, it is not obvious that a codebase with both could be compliant with the standard.

**Comment by Ainali** [comment]
Here are the notes from the community call where this issue was discussed: https://blog.publiccode.net/community%20call/2023/12/11/notes-from-community-call-7-december-2023.html
