### ISSUE TITLE
Add ISO ambitions to roadmap?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#998]
Following our [community call in October](https://blog.publiccode.net/community%20call/2023/10/09/notes-from-community-call-5-october-2023.html), should we add ambitions to become an ISO standard under the long-term ambitions in the [roadmap](https://github.com/publiccodenet/standard/blob/develop/docs/roadmap.md)?

**Comment by ericherman** [comment]
Absolutely.
